// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
// AUTO-GENERATED by azihsm_reggen — do not edit.

//! Register definitions for aes.
//!
//! 'AES symmetric block cipher accelerator (single instance). Descriptor-driven dispatch model identical to UPKA/SHA. Base address 0xA020_0000.'

pub const AES_BASE: u32 = 0xA0200000;
pub const COMMAND_OFFSET: u32 = 0x00;
pub const STATUS_OFFSET: u32 = 0x04;

tock_registers::register_bitfields! [u32,
    /// 'Descriptor doorbell. Writing this register triggers the engine to fetch the 24-byte AesCmdDesc descriptor located at the written AXI address and start executing the requested operation. The descriptor must be 4-byte aligned and remain valid until STATUS reports completion.'
    pub COMMAND [
        /// 'AXI address of the AesCmdDesc descriptor. Reads return the last-written value (not consumed by hardware on read). Writes act as the doorbell that triggers the engine to fetch the descriptor.'
        DESC_ADDR OFFSET(0) NUMBITS(32) [],
    ],
    /// 'Engine status. Polled by firmware between submit and completion; latched by the engine on every state transition. A Done or Error IRQ fires on every command completion (positive and negative).'
    pub STATUS [
        /// 'Engine is currently processing a command. Cleared on completion (success or error). Firmware must NOT write the COMMAND register while BUSY is set.'
        BUSY OFFSET(0) NUMBITS(1) [],
        /// 'Engine successfully finished the most recent command. Mutually exclusive with the ERROR_* bits.'
        COMPLETE OFFSET(1) NUMBITS(1) [],
        /// 'Engine could not decode the command structure successfully (invalid opcode, bad descriptor layout).'
        ERROR_CMD OFFSET(2) NUMBITS(1) [],
        /// 'Engine encountered an error initiating an AXI bus transaction (e.g. SLVERR / DECERR on a result, input buffer, or descriptor fetch).'
        ERROR_BUS OFFSET(3) NUMBITS(1) [],
        /// 'Engine detected an internal fault while working on the operation (parity, lane-fault, or engine-fault).'
        ERROR_FAULT OFFSET(4) NUMBITS(1) [],
        /// 'Engine is/was working on a command initiated by a different bus master than the one reading the STATUS register. Driver masks this bit out of completion decode (mirrors UPKA/SHA pattern).'
        NOT_OWNER OFFSET(5) NUMBITS(1) [],
        RSVD_0 OFFSET(6) NUMBITS(26) [],
    ]
];

pub mod regs {
    //! MMIO register struct for firmware use.
    tock_registers::register_structs! {
        pub AesRegs {
            (0x0 => pub command: crate::RW<u32, super::COMMAND::Register>),
            (0x4 => pub status: crate::RO<u32, super::STATUS::Register>),
            (0x8 => @END),
        }
    }
}
