// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
// AUTO-GENERATED by azihsm_reggen — do not edit.

//! Register definitions for dual_cp_m7.
//!
//! 'Dual Cortex-M7 control block. Exposes CP_ID for boot-time core identification by the dual-core trampoline.'

pub const DUAL_CP_M7_BASE: u32 = 0xB0200000;
pub const CP_ID_OFFSET: u32 = 0x00;

tock_registers::register_bitfields! [u32,
    /// 'Identifies the core (initiator) that issued the read. The value returned depends on the read initiator: HSP = 1, CP0 (Admin) = 2, CP1 (HSM) = 3.'
    pub CP_ID [
        /// 'Initiator ID of the core that performed the read.'
        INITIATOR_ID OFFSET(0) NUMBITS(6) [],
    ]
];

pub mod regs {
    //! MMIO register struct for firmware use.
    tock_registers::register_structs! {
        pub DualCpM7Regs {
            (0x0 => pub cp_id: crate::RO<u32, super::CP_ID::Register>),
            (0x4 => @END),
        }
    }
}
