// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
// AUTO-GENERATED by azihsm_reggen — do not edit.

//! Register definitions for gdma.
//!
//! 'GDMA Channel register map — single bank (4 channels).  Multi-bank SoCs instantiate at stride 0x200. bank[0] = channels 0-3 bank[1] = channels 4-7 (at +0x200)  SQ entry = 64 bytes, CQ entry = 16 bytes. Depth is raw 13-bit (max 4096). Head/Tail are 12-bit.'

pub const GDMA_BASE: u32 = 0xA0000000;
pub const SQ_CTRL_OFFSET: u32 = 0x20;
pub const CQ_CTRL_OFFSET: u32 = 0x30;
pub const IRQ_ENABLE_OFFSET: u32 = 0x484;
pub const SQ_OFFSET: u32 = 0x40;
pub const SQ_COUNT: u32 = 4;
pub const SQ_STRIDE: u32 = 0x20;
pub const CQ_OFFSET: u32 = 0x100;
pub const CQ_COUNT: u32 = 4;
pub const CQ_STRIDE: u32 = 0x20;

tock_registers::register_bitfields! [u32,
    /// 'SQ enable, head-shadow enable, depth, interface select.'
    pub SQ_CTRL [
        /// 'Queue depth (max 4096 entries).'
        DEPTH OFFSET(0) NUMBITS(13) [],
        RSVD_1 OFFSET(13) NUMBITS(3) [],
        /// 'AXI port where SQ and optional head shadow reside.'
        IFC_SLCT OFFSET(16) NUMBITS(8) [],
        RSVD_0 OFFSET(24) NUMBITS(6) [],
        HEAD_SHADOW_EN OFFSET(30) NUMBITS(1) [],
        EN OFFSET(31) NUMBITS(1) [],
    ],
    /// 'CQ enable, tail-shadow enable, depth, interface select.'
    pub CQ_CTRL [
        /// 'Queue depth.'
        DEPTH OFFSET(0) NUMBITS(13) [],
        RSVD_1 OFFSET(13) NUMBITS(3) [],
        /// 'AXI port where CQ resides.'
        IFC_SLCT OFFSET(16) NUMBITS(8) [],
        RSVD_0 OFFSET(24) NUMBITS(6) [],
        TAIL_SHADOW_EN OFFSET(30) NUMBITS(1) [],
        EN OFFSET(31) NUMBITS(1) [],
    ],
    /// 'Per-channel CQ interrupt enable. Bit N = channel N.'
    pub IRQ_ENABLE [
        IRQ_EN OFFSET(0) NUMBITS(32) [],
    ],
    /// 'SQ Tail — SW advances after enqueuing a descriptor.'
    pub SQ_CHANNEL_TAIL [
        TAIL OFFSET(0) NUMBITS(12) [],
        RSVD_0 OFFSET(12) NUMBITS(20) [],
    ],
    /// 'SQ Head — HW advances after consuming a descriptor. Read-only for SW.'
    pub SQ_CHANNEL_HEAD [
        HEAD OFFSET(0) NUMBITS(12) [],
        RSVD_0 OFFSET(12) NUMBITS(20) [],
    ],
    /// 'CQ Tail — HW advances after posting a completion. Read-only for SW.'
    pub CQ_CHANNEL_TAIL [
        TAIL OFFSET(0) NUMBITS(12) [],
        RSVD_0 OFFSET(12) NUMBITS(20) [],
    ],
    /// 'CQ Head — SW advances after consuming a completion.'
    pub CQ_CHANNEL_HEAD [
        HEAD OFFSET(0) NUMBITS(12) [],
        RSVD_0 OFFSET(12) NUMBITS(20) [],
    ]
];

/// Regfile entry struct for `sq_channel`.
#[repr(C)]
pub struct SqChannel {
    pub base_lo: crate::RW<u32>,
    pub base_hi: crate::RW<u32>,
    pub head_shadow: crate::RW<u32>,
    pub tail: crate::RW<u32, SQ_CHANNEL_TAIL::Register>,
    pub head: crate::RW<u32, SQ_CHANNEL_HEAD::Register>,
    _pad0: [u32; 3],
}

/// Regfile entry struct for `cq_channel`.
#[repr(C)]
pub struct CqChannel {
    pub base_lo: crate::RW<u32>,
    pub base_hi: crate::RW<u32>,
    pub tail_shadow: crate::RW<u32>,
    pub tail: crate::RW<u32, CQ_CHANNEL_TAIL::Register>,
    pub head: crate::RW<u32, CQ_CHANNEL_HEAD::Register>,
    _pad0: [u32; 3],
}

pub mod regs {
    //! MMIO register struct for firmware use.
    tock_registers::register_structs! {
        pub GdmaRegs {
            (0x0 => _reserved0),
            (0x20 => pub sq_ctrl: [crate::RW<u32, super::SQ_CTRL::Register>; 4]),
            (0x30 => pub cq_ctrl: [crate::RW<u32, super::CQ_CTRL::Register>; 4]),
            (0x40 => pub sq: [super::SqChannel; 4]),
            (0xc0 => _reserved1),
            (0x100 => pub cq: [super::CqChannel; 4]),
            (0x180 => _reserved2),
            (0x484 => pub irq_enable: crate::RW<u32, super::IRQ_ENABLE::Register>),
            (0x488 => @END),
        }
    }
}
