// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
// AUTO-GENERATED by azihsm_reggen — do not edit.

//! Register definitions for hsm_dtcm.
//!
//! 'HSM local DTCM (256 KB at 0x2000_0000). Upper region holds per-IO scratch buffers and status/crashdump registers. Lower 189 KB is linker-managed (stack + .bss).'

pub const HSM_DTCM_BASE: u32 = 0x20000000;
pub const CORE_RUN_STATUS_OFFSET: u32 = 0x3F800;
pub const DTCM_IO_BUF_OFFSET: u32 = 0x2F400;
pub const DTCM_IO_BUF_COUNT: u32 = 32;
pub const DTCM_IO_BUF_STRIDE: u32 = 0x800;
pub const DTCM_IO_BUF_SIZE: u32 = 0x800;
pub const CRASHDUMP_BASE_OFFSET: u32 = 0x3F400;
pub const CRASHDUMP_BASE_COUNT: u32 = 1;
pub const CRASHDUMP_BASE_STRIDE: u32 = 0x400;
pub const CRASHDUMP_BASE_SIZE: u32 = 0x400;

tock_registers::register_bitfields! [u32,
    /// 'Liveliness heartbeat. HSM writes 1 periodically; SP reads then zeroes. Zero on next poll = hung.'
    pub CORE_RUN_STATUS [
        ALIVE OFFSET(0) NUMBITS(32) [],
    ]
];

pub mod regs {
    //! MMIO register struct for firmware use.
    tock_registers::register_structs! {
        pub HsmDtcmRegs {
            (0x0 => _reserved0),
            (0x2f400 => pub dtcm_io_buf: [u8; 65536]),
            (0x3f400 => pub crashdump_base: [u8; 1024]),
            (0x3f800 => pub core_run_status: crate::RW<u32, super::CORE_RUN_STATUS::Register>),
            (0x3f804 => @END),
        }
    }
}
