// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
// AUTO-GENERATED by azihsm_reggen — do not edit.

//! Register definitions for iic.
//!
//! 'Inbound IO Controller — single controller register map. Two instances exist at 0xA128_0000 stride 0x4000.  controller[0] = Core0 (Core0) controller[1] = Core1 (Fast Path)'

pub const IIC_BASE: u32 = 0xA1280000;
pub const INTERRUPT_CAUSE_OFFSET: u32 = 0x0C;
pub const IRQ_ENABLE_OFFSET: u32 = 0x10;
pub const ISQ_CH_OFFSET: u32 = 0x60;
pub const ISQ_CH_COUNT: u32 = 6;
pub const ISQ_CH_STRIDE: u32 = 0x20;
pub const ICQ_CH_OFFSET: u32 = 0x120;
pub const ICQ_CH_COUNT: u32 = 5;
pub const ICQ_CH_STRIDE: u32 = 0x30;
pub const IQ_OFFSET: u32 = 0x1000;
pub const IQ_COUNT: u32 = 132;
pub const IQ_STRIDE: u32 = 0x40;

tock_registers::register_bitfields! [u32,
    /// 'Inbound interrupt cause bitmap. Read to identify the source of an inbound error. Bits include: IQ soft error, DFL empty per channel, DFL overflow per channel, etc.'
    pub INTERRUPT_CAUSE [
        CAUSE OFFSET(0) NUMBITS(32) [],
    ],
    /// 'Per-channel IRQ enable bitmask (bit N = channel N).'
    pub IRQ_ENABLE [
        IRQ_EN OFFSET(0) NUMBITS(32) [],
    ],
    /// 'ISQ enable, depth, buffer length.'
    pub ISQ_CHANNEL_CTRL [
        EN OFFSET(0) NUMBITS(1) [],
        RSVD_2 OFFSET(1) NUMBITS(7) [],
        DEPTH OFFSET(8) NUMBITS(4) [],
        RSVD_1 OFFSET(12) NUMBITS(4) [],
        BUF_LEN OFFSET(16) NUMBITS(12) [],
        RSVD_0 OFFSET(28) NUMBITS(4) [],
    ],
    /// 'AXI interface select for buffers and list.'
    pub ISQ_CHANNEL_IFC_SLCT [
        BUF_IFC_SLCT OFFSET(0) NUMBITS(8) [],
        LIST_IFC_SLCT OFFSET(8) NUMBITS(8) [],
        RSVD_0 OFFSET(16) NUMBITS(16) [],
    ],
    /// 'Lower 32 bits of ISQ base address (8B-aligned).'
    pub ISQ_CHANNEL_BASE_LO [
        RSVD_0 OFFSET(0) NUMBITS(3) [],
        ADDR OFFSET(3) NUMBITS(29) [],
    ],
    /// 'ISQ Tail — FW advances after posting buffer address.'
    pub ISQ_CHANNEL_TAIL [
        TAIL OFFSET(0) NUMBITS(16) [],
        RSVD_0 OFFSET(16) NUMBITS(16) [],
    ],
    /// 'ISQ Head — HW advances after consuming buffer address.'
    pub ISQ_CHANNEL_HEAD [
        HEAD OFFSET(0) NUMBITS(16) [],
        RSVD_0 OFFSET(16) NUMBITS(16) [],
    ],
    /// 'ISQ status — empty indication.'
    pub ISQ_CHANNEL_STATUS [
        EMPTY OFFSET(0) NUMBITS(1) [],
        RSVD_0 OFFSET(1) NUMBITS(31) [],
    ],
    /// 'ICQ enable, shadow enable, depth, interface select.'
    pub ICQ_CHANNEL_CTRL [
        EN OFFSET(0) NUMBITS(1) [],
        SHADOW_EN OFFSET(1) NUMBITS(1) [],
        RSVD_2 OFFSET(2) NUMBITS(6) [],
        DEPTH OFFSET(8) NUMBITS(4) [],
        RSVD_1 OFFSET(12) NUMBITS(4) [],
        IFC_SLCT OFFSET(16) NUMBITS(8) [],
        RSVD_0 OFFSET(24) NUMBITS(8) [],
    ],
    /// 'Lower 32 bits of tail shadow address (4B-aligned).'
    pub ICQ_CHANNEL_TAIL_SHADOW_LO [
        RSVD_0 OFFSET(0) NUMBITS(2) [],
        ADDR OFFSET(2) NUMBITS(30) [],
    ],
    /// 'Lower 32 bits of ICQ base address (4B-aligned).'
    pub ICQ_CHANNEL_BASE_LO [
        RSVD_0 OFFSET(0) NUMBITS(2) [],
        ADDR OFFSET(2) NUMBITS(30) [],
    ],
    /// 'ICQ Tail — HW advances after posting entry. FW writes 0 at init.'
    pub ICQ_CHANNEL_TAIL [
        TAIL OFFSET(0) NUMBITS(16) [],
        RSVD_0 OFFSET(16) NUMBITS(16) [],
    ],
    /// 'ICQ Head — FW advances after consuming entries.'
    pub ICQ_CHANNEL_HEAD [
        HEAD OFFSET(0) NUMBITS(16) [],
        RSVD_1 OFFSET(16) NUMBITS(14) [],
        INTRPT_CLR OFFSET(30) NUMBITS(1) [],
        RSVD_0 OFFSET(31) NUMBITS(1) [],
    ],
    /// 'Per-queue credit count. HW decrements on fetch, FW increments after processing via RMW.'
    pub IQ_QUEUE_CREDIT [
        CREDIT OFFSET(0) NUMBITS(8) [],
        RSVD_0 OFFSET(8) NUMBITS(24) [],
    ]
];

/// Regfile entry struct for `isq_channel`.
#[repr(C)]
pub struct IsqChannel {
    pub ctrl: crate::RW<u32, ISQ_CHANNEL_CTRL::Register>,
    pub ifc_slct: crate::RW<u32, ISQ_CHANNEL_IFC_SLCT::Register>,
    pub base_lo: crate::RW<u32, ISQ_CHANNEL_BASE_LO::Register>,
    pub base_hi: crate::RW<u32>,
    pub tail: crate::RW<u32, ISQ_CHANNEL_TAIL::Register>,
    pub head: crate::RW<u32, ISQ_CHANNEL_HEAD::Register>,
    pub status: crate::RW<u32, ISQ_CHANNEL_STATUS::Register>,
    _pad0: u32,
}

/// Regfile entry struct for `icq_channel`.
#[repr(C)]
pub struct IcqChannel {
    pub ctrl: crate::RW<u32, ICQ_CHANNEL_CTRL::Register>,
    _pad0: [u32; 3],
    pub tail_shadow_lo: crate::RW<u32, ICQ_CHANNEL_TAIL_SHADOW_LO::Register>,
    pub tail_shadow_hi: crate::RW<u32>,
    pub base_lo: crate::RW<u32, ICQ_CHANNEL_BASE_LO::Register>,
    pub base_hi: crate::RW<u32>,
    pub tail: crate::RW<u32, ICQ_CHANNEL_TAIL::Register>,
    pub head: crate::RW<u32, ICQ_CHANNEL_HEAD::Register>,
    _pad1: [u32; 2],
}

/// Regfile entry struct for `iq_queue`.
#[repr(C)]
pub struct IqQueue {
    _pad0: [u32; 2],
    pub credit: crate::RW<u32, IQ_QUEUE_CREDIT::Register>,
    _pad1: [u32; 13],
}

pub mod regs {
    //! MMIO register struct for firmware use.
    tock_registers::register_structs! {
        pub IicRegs {
            (0x0 => _reserved0),
            (0xc => pub interrupt_cause: crate::RO<u32, super::INTERRUPT_CAUSE::Register>),
            (0x10 => pub irq_enable: crate::RW<u32, super::IRQ_ENABLE::Register>),
            (0x14 => _reserved1),
            (0x60 => pub isq_ch: [super::IsqChannel; 6]),
            (0x120 => pub icq_ch: [super::IcqChannel; 5]),
            (0x210 => _reserved2),
            (0x1000 => pub iq: [super::IqQueue; 132]),
            (0x3100 => @END),
        }
    }
}
