// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
// AUTO-GENERATED by azihsm_reggen — do not edit.

//! Register definitions for intc.
//!
//! 'IPC Interrupt Controller with 6 interrupt control blocks and 32 doorbell descriptor registers. Total register space: 0x110 bytes.'

pub const INTC_BASE: u32 = 0xB0006000;
pub const PEND_CLR_OFFSET: u32 = 0x00;
pub const PEND_SET_OFFSET: u32 = 0x18;
pub const MASK_CLR_OFFSET: u32 = 0x30;
pub const MASK_SET_OFFSET: u32 = 0x48;
pub const ENABLE_CLR_OFFSET: u32 = 0x60;
pub const ENABLE_SET_OFFSET: u32 = 0x78;
pub const DESC_OFFSET: u32 = 0x110;

tock_registers::register_bitfields! [u32,
    /// 'Write 1 to bit N to clear descriptor N's pending status. Original: pend_clr'
    pub PEND_CLR [
        BITS OFFSET(0) NUMBITS(32) [],
    ],
    /// 'Read pending status. Bit N = 1 means descriptor N is pending. Original: pend_set'
    pub PEND_SET [
        BITS OFFSET(0) NUMBITS(32) [],
    ],
    /// 'Write 1 to bit N to unmask descriptor N. Original: mask_clr'
    pub MASK_CLR [
        BITS OFFSET(0) NUMBITS(32) [],
    ],
    /// 'Write 1 to bit N to mask descriptor N. Original: mask_set'
    pub MASK_SET [
        BITS OFFSET(0) NUMBITS(32) [],
    ],
    /// 'Write 1 to bit N to disable descriptor N's IRQ. Original: enable_clr'
    pub ENABLE_CLR [
        BITS OFFSET(0) NUMBITS(32) [],
    ],
    /// 'Write 1 to bit N to enable descriptor N's IRQ. Original: enable_set'
    pub ENABLE_SET [
        BITS OFFSET(0) NUMBITS(32) [],
    ],
    /// 'Doorbell + value register. Writing triggers pending IRQ on all blocks that have this descriptor enabled. Original: desc_t'
    pub DESC [
        VALUE OFFSET(0) NUMBITS(32) [],
    ]
];

pub mod regs {
    //! MMIO register struct for firmware use.
    tock_registers::register_structs! {
        pub IntcRegs {
            (0x0 => pub pend_clr: [crate::RW<u32, super::PEND_CLR::Register>; 6]),
            (0x18 => pub pend_set: [crate::RO<u32, super::PEND_SET::Register>; 6]),
            (0x30 => pub mask_clr: [crate::RW<u32, super::MASK_CLR::Register>; 6]),
            (0x48 => pub mask_set: [crate::RW<u32, super::MASK_SET::Register>; 6]),
            (0x60 => pub enable_clr: [crate::RW<u32, super::ENABLE_CLR::Register>; 6]),
            (0x78 => pub enable_set: [crate::RW<u32, super::ENABLE_SET::Register>; 6]),
            (0x90 => _reserved0),
            (0x110 => pub desc: [crate::RW<u32, super::DESC::Register>; 32]),
            (0x190 => @END),
        }
    }
}
