// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
// AUTO-GENERATED by azihsm_reggen — do not edit.

//! Register definitions for oic.
//!
//! 'Outbound IO Controller — single controller register map. Two instances exist at 0xA12C_0000 stride 0x4000. controller[0] = Core0 (Core0) controller[1] = Core1 (Fast Path)'

pub const OIC_BASE: u32 = 0xA12C0000;
pub const IRQ_ENABLE_OFFSET: u32 = 0x10;
pub const OSQ_CH_OFFSET: u32 = 0x70;
pub const OSQ_CH_COUNT: u32 = 5;
pub const OSQ_CH_STRIDE: u32 = 0x20;
pub const OCQ_CH_OFFSET: u32 = 0x120;
pub const OCQ_CH_COUNT: u32 = 5;
pub const OCQ_CH_STRIDE: u32 = 0x30;
pub const OQ_OFFSET: u32 = 0x1000;
pub const OQ_COUNT: u32 = 132;
pub const OQ_STRIDE: u32 = 0x40;

tock_registers::register_bitfields! [u32,
    /// 'Per-channel IRQ enable bitmask (bit N = channel N).'
    pub IRQ_ENABLE [
        IRQ_EN OFFSET(0) NUMBITS(32) [],
    ],
    /// 'OSQ enable, depth, interface select.'
    pub OSQ_CHANNEL_CTRL [
        EN OFFSET(0) NUMBITS(1) [],
        RSVD_2 OFFSET(1) NUMBITS(7) [],
        DEPTH OFFSET(8) NUMBITS(4) [],
        RSVD_1 OFFSET(12) NUMBITS(4) [],
        IFC_SLCT OFFSET(16) NUMBITS(8) [],
        RSVD_0 OFFSET(24) NUMBITS(8) [],
    ],
    /// 'Lower 32 bits of OSQ base address (32B-aligned).'
    pub OSQ_CHANNEL_BASE_LO [
        RSVD_0 OFFSET(0) NUMBITS(5) [],
        ADDR OFFSET(5) NUMBITS(27) [],
    ],
    /// 'OSQ Tail — FW advances after posting TX descriptor.'
    pub OSQ_CHANNEL_TAIL [
        TAIL OFFSET(0) NUMBITS(16) [],
        RSVD_0 OFFSET(16) NUMBITS(16) [],
    ],
    /// 'OSQ Head — HW advances after consuming TX descriptor.'
    pub OSQ_CHANNEL_HEAD [
        HEAD OFFSET(0) NUMBITS(16) [],
        RSVD_0 OFFSET(16) NUMBITS(16) [],
    ],
    /// 'OSQ status — empty indication.'
    pub OSQ_CHANNEL_STATUS [
        EMPTY OFFSET(0) NUMBITS(1) [],
        RSVD_0 OFFSET(1) NUMBITS(31) [],
    ],
    /// 'OCQ enable, shadow enable, depth, interface select.'
    pub OCQ_CHANNEL_CTRL [
        EN OFFSET(0) NUMBITS(1) [],
        SHADOW_EN OFFSET(1) NUMBITS(1) [],
        RSVD_2 OFFSET(2) NUMBITS(6) [],
        DEPTH OFFSET(8) NUMBITS(4) [],
        RSVD_1 OFFSET(12) NUMBITS(4) [],
        IFC_SLCT OFFSET(16) NUMBITS(8) [],
        RSVD_0 OFFSET(24) NUMBITS(8) [],
    ],
    /// 'Lower 32 bits of tail shadow address (4B-aligned).'
    pub OCQ_CHANNEL_TAIL_SHADOW_LO [
        RSVD_0 OFFSET(0) NUMBITS(2) [],
        ADDR OFFSET(2) NUMBITS(30) [],
    ],
    /// 'Lower 32 bits of OCQ base address (32B-aligned).'
    pub OCQ_CHANNEL_BASE_LO [
        RSVD_0 OFFSET(0) NUMBITS(5) [],
        ADDR OFFSET(5) NUMBITS(27) [],
    ],
    /// 'OCQ Tail — HW advances after posting entry. FW reads.'
    pub OCQ_CHANNEL_TAIL [
        TAIL OFFSET(0) NUMBITS(16) [],
        RSVD_0 OFFSET(16) NUMBITS(16) [],
    ],
    /// 'OCQ Head — FW advances after consuming entries.'
    pub OCQ_CHANNEL_HEAD [
        HEAD OFFSET(0) NUMBITS(16) [],
        RSVD_1 OFFSET(16) NUMBITS(14) [],
        INTRPT_CLR OFFSET(30) NUMBITS(1) [],
        RSVD_0 OFFSET(31) NUMBITS(1) [],
    ],
    /// 'Per-queue credit count. HW decrements on fetch, FW increments after processing via RMW.'
    pub OQ_QUEUE_CREDIT [
        CREDIT OFFSET(0) NUMBITS(8) [],
        RSVD_0 OFFSET(8) NUMBITS(24) [],
    ]
];

/// Regfile entry struct for `osq_channel`.
#[repr(C)]
pub struct OsqChannel {
    pub ctrl: crate::RW<u32, OSQ_CHANNEL_CTRL::Register>,
    _pad0: u32,
    pub base_lo: crate::RW<u32, OSQ_CHANNEL_BASE_LO::Register>,
    pub base_hi: crate::RW<u32>,
    pub tail: crate::RW<u32, OSQ_CHANNEL_TAIL::Register>,
    pub head: crate::RW<u32, OSQ_CHANNEL_HEAD::Register>,
    pub status: crate::RO<u32, OSQ_CHANNEL_STATUS::Register>,
    _pad1: u32,
}

/// Regfile entry struct for `ocq_channel`.
#[repr(C)]
pub struct OcqChannel {
    pub ctrl: crate::RW<u32, OCQ_CHANNEL_CTRL::Register>,
    _pad0: [u32; 2],
    pub tail_shadow_lo: crate::RW<u32, OCQ_CHANNEL_TAIL_SHADOW_LO::Register>,
    pub tail_shadow_hi: crate::RW<u32>,
    pub base_lo: crate::RW<u32, OCQ_CHANNEL_BASE_LO::Register>,
    pub base_hi: crate::RW<u32>,
    pub tail: crate::RW<u32, OCQ_CHANNEL_TAIL::Register>,
    pub head: crate::RW<u32, OCQ_CHANNEL_HEAD::Register>,
    _pad1: [u32; 3],
}

/// Regfile entry struct for `oq_queue`.
#[repr(C)]
pub struct OqQueue {
    _pad0: [u32; 2],
    pub credit: crate::RW<u32, OQ_QUEUE_CREDIT::Register>,
    _pad1: [u32; 13],
}

pub mod regs {
    //! MMIO register struct for firmware use.
    tock_registers::register_structs! {
        pub OicRegs {
            (0x0 => _reserved0),
            (0x10 => pub irq_enable: crate::RW<u32, super::IRQ_ENABLE::Register>),
            (0x14 => _reserved1),
            (0x70 => pub osq_ch: [super::OsqChannel; 5]),
            (0x110 => _reserved2),
            (0x120 => pub ocq_ch: [super::OcqChannel; 5]),
            (0x210 => _reserved3),
            (0x1000 => pub oq: [super::OqQueue; 132]),
            (0x3100 => @END),
        }
    }
}
