// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
// AUTO-GENERATED by azihsm_reggen — do not edit.

//! Register definitions for part_store_t.
//!
//! 'Per-partition persistent store (3072 B), mirroring the reference firmware's HsmPartPersistentStore with Uno-specific fields appended into the trailing reserved region.'

pub const PART_STORE_T_BASE: u32 = 0x000BB000;
pub const DATA_OFFSET: u32 = 0x00;

tock_registers::register_bitfields! [u32,
    /// 'One 32-bit word of the per-partition persistent store. The typed field layout (reference HsmPartPersistentStore plus the Uno-specific working-state fields) is owned by the part_store driver, not described here.'
    pub DATA [
        VAL OFFSET(0) NUMBITS(32) [],
    ]
];

pub mod regs {
    //! MMIO register struct for firmware use.
    tock_registers::register_structs! {
        pub PartStoreTRegs {
            (0x0 => pub data: [crate::RW<u32, super::DATA::Register>; 768]),
            (0xc00 => @END),
        }
    }
}
