// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
// AUTO-GENERATED by azihsm_reggen — do not edit.

//! Register definitions for psram.
//!
//! 'CP0/CP1↔backend shared SRAM.  Only the HSM-visible IPC rings and their producer/consumer indices are modelled here; Admin-side regions are intentionally omitted.'

pub const PSRAM_BASE: u32 = 0xA3E00000;
pub const HSM_TO_FP_IPC_TX_PI_OFFSET: u32 = 0x3BD4;
pub const HSM_TO_FP_IPC_TX_CI_OFFSET: u32 = 0x3BD8;
pub const HSM_TO_FP_IPC_RX_PI_OFFSET: u32 = 0x3BDC;
pub const HSM_TO_FP_IPC_RX_CI_OFFSET: u32 = 0x3BE0;
pub const HSM_TO_FP_IPC_TX_RING_OFFSET: u32 = 0x980;
pub const HSM_TO_FP_IPC_TX_RING_COUNT: u32 = 16;
pub const HSM_TO_FP_IPC_TX_RING_STRIDE: u32 = 0x40;
pub const HSM_TO_FP_IPC_RX_RING_OFFSET: u32 = 0xD80;
pub const HSM_TO_FP_IPC_RX_RING_COUNT: u32 = 16;
pub const HSM_TO_FP_IPC_RX_RING_STRIDE: u32 = 0x40;

tock_registers::register_bitfields! [u32,
    /// 'Producer or consumer index for a PSRAM IPC ring.'
    pub HSM_TO_FP_IPC_TX_PI [
        VAL OFFSET(0) NUMBITS(32) [],
    ],
    /// 'Producer or consumer index for a PSRAM IPC ring.'
    pub HSM_TO_FP_IPC_TX_CI [
        VAL OFFSET(0) NUMBITS(32) [],
    ],
    /// 'Producer or consumer index for a PSRAM IPC ring.'
    pub HSM_TO_FP_IPC_RX_PI [
        VAL OFFSET(0) NUMBITS(32) [],
    ],
    /// 'Producer or consumer index for a PSRAM IPC ring.'
    pub HSM_TO_FP_IPC_RX_CI [
        VAL OFFSET(0) NUMBITS(32) [],
    ]
];

/// Regfile entry struct for `psram_ipc_message`.
#[repr(C)]
pub struct PsramIpcMessage {
    pub dw0: crate::RW<u32>,
    pub dw1: crate::RW<u32>,
    pub dw2: crate::RW<u32>,
    pub dw3: crate::RW<u32>,
    pub dw4: crate::RW<u32>,
    pub dw5: crate::RW<u32>,
    pub dw6: crate::RW<u32>,
    pub dw7: crate::RW<u32>,
    pub dw8: crate::RW<u32>,
    pub dw9: crate::RW<u32>,
    pub dw10: crate::RW<u32>,
    pub dw11: crate::RW<u32>,
    pub dw12: crate::RW<u32>,
    pub dw13: crate::RW<u32>,
    pub dw14: crate::RW<u32>,
    pub dw15: crate::RW<u32>,
}

pub mod regs {
    //! MMIO register struct for firmware use.
    tock_registers::register_structs! {
        pub PsramRegs {
            (0x0 => _reserved0),
            (0x980 => pub hsm_to_fp_ipc_tx_ring: [super::PsramIpcMessage; 16]),
            (0xd80 => pub hsm_to_fp_ipc_rx_ring: [super::PsramIpcMessage; 16]),
            (0x1180 => _reserved1),
            (0x3bd4 => pub hsm_to_fp_ipc_tx_pi: crate::RW<u32, super::HSM_TO_FP_IPC_TX_PI::Register>),
            (0x3bd8 => pub hsm_to_fp_ipc_tx_ci: crate::RW<u32, super::HSM_TO_FP_IPC_TX_CI::Register>),
            (0x3bdc => pub hsm_to_fp_ipc_rx_pi: crate::RW<u32, super::HSM_TO_FP_IPC_RX_PI::Register>),
            (0x3be0 => pub hsm_to_fp_ipc_rx_ci: crate::RW<u32, super::HSM_TO_FP_IPC_RX_CI::Register>),
            (0x3be4 => @END),
        }
    }
}
