// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
// AUTO-GENERATED by azihsm_reggen — do not edit.

//! Register definitions for psram.
//!
//! 'Persistent SRAM (32 KB at 0xA3E0_0000). Survives warm reset; shared SP/CP/FP region. uno models only the reset-reason word.'

pub const PSRAM_BASE: u32 = 0xA3E00000;
pub const RESET_TYPE_OFFSET: u32 = 0x3AFC;

tock_registers::register_bitfields! [u32,
    /// 'SoC reset reason published by the boot processor (SP) before releasing the CP cores. 0 = POR, 1 = warm reset, 2 = fw-update warm reset. Read-only from the CP; the HSM reads it at boot to gate destructive partition-store init (recovery boot).'
    pub RESET_TYPE [
        RESET_TYPE OFFSET(0) NUMBITS(32) [],
    ]
];

pub mod regs {
    //! MMIO register struct for firmware use.
    tock_registers::register_structs! {
        pub PsramRegs {
            (0x0 => _reserved0),
            (0x3afc => pub reset_type: crate::RO<u32, super::RESET_TYPE::Register>),
            (0x3b00 => @END),
        }
    }
}
