// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
// AUTO-GENERATED by azihsm_reggen — do not edit.

//! Register definitions for rng.
//!
//! 'CTR_DRBG-style RNG with TRBG entropy source, per-output health tests, and DAS / FW-mode backdoors for self-testing.  Base address: 0xA030_0000 (per legacy spec; confirm with silicon RDL). Total register space: 0x1000 (4 KB).  Driver uses: CTRL.ENABLE             — enable RNG STATUS.BUSY             — poll before reading RN_DATA RN_DATA                 — read random word STATUS.*_FAULT_ERROR    — health-test fault flags'

pub const RNG_BASE: u32 = 0xA0300000;
pub const CTRL_OFFSET: u32 = 0x00;
pub const DAS_EN_OFFSET: u32 = 0x04;
pub const DAS_DATA_OFFSET: u32 = 0x08;
pub const STATUS_OFFSET: u32 = 0x0C;
pub const RESEED_INTERVAL_OFFSET: u32 = 0x10;
pub const GENERATE_INTERVAL_OFFSET: u32 = 0x14;
pub const RESEED_CNT_OFFSET: u32 = 0x18;
pub const GENERATE_CNT_OFFSET: u32 = 0x1C;
pub const DRBG_STATUS_OFFSET: u32 = 0x20;
pub const CLK_DIV_MSB_OFFSET: u32 = 0x24;
pub const REPCNT_CUTOFF_OFFSET: u32 = 0x30;
pub const APT_CUTOFF_OFFSET: u32 = 0x34;
pub const CHISQ_CUTOFF_OFFSET: u32 = 0x38;
pub const K_OFFSET: u32 = 0x100;
pub const V_OFFSET: u32 = 0x140;
pub const RN_DATA_OFFSET: u32 = 0x200;
pub const FWIN_DATA_OFFSET: u32 = 0x400;
pub const FWOUT_DATA_OFFSET: u32 = 0x600;

tock_registers::register_bitfields! [u32,
    /// 'RNG main control. Enables the block, selects FW vs HW DRBG mode, and exposes the DRBG state-machine triggers used in FW mode.'
    pub CTRL [
        /// 'Lower 8 bits of the TRBG clock divider ratio. The TRBG generates a new bit every time its internal counter reaches {CLK_DIV_MSB[1:0], CLK_DIV[7:0], 8'b00}.'
        CLK_DIV OFFSET(0) NUMBITS(8) [],
        /// 'Master enable for the RNG block. Must be set to 1 early during boot before any random data can be read.'
        ENABLE OFFSET(8) NUMBITS(1) [],
        /// 'FW mode. When set, DRBG inputs/outputs route through the FW FIFOs (FWIN_DATA / FWOUT_DATA) instead of the hardware entropy path. Toggling this clears the FW FIFOs and DRBG state.'
        FW_MODE OFFSET(9) NUMBITS(1) [],
        /// 'DRBG instantiate. In FW mode with the FWIN FIFO full, asserting this triggers a DRBG instantiate operation.'
        DRBG_INSTANTIATE OFFSET(10) NUMBITS(1) [],
        /// 'DRBG generate. In FW mode with the DRBG instantiated, asserting this triggers generate operations to fill the FWOUT FIFO.'
        DRBG_GENERATE OFFSET(11) NUMBITS(1) [],
        /// 'DRBG uninstantiate. Asserting this in FW mode clears the DRBG state. Takes precedence over DRBG_INSTANTIATE and DRBG_GENERATE.'
        DRBG_UNINSTANTIATE OFFSET(12) NUMBITS(1) [],
        RSVD_0 OFFSET(13) NUMBITS(19) [],
    ],
    /// 'Direct Access Slave enable. Writing 0xDA enables the DAS backdoor that lets firmware read TRBG entropy directly (used for entropy validation and ACVP).'
    pub DAS_EN [
        /// 'DAS enable code. DAS is enabled when the value is 0xDA.'
        CODE OFFSET(0) NUMBITS(8) [],
        RSVD_0 OFFSET(8) NUMBITS(24) [],
    ],
    /// 'Raw entropy word read directly from the TRBG when the DAS backdoor is enabled.'
    pub DAS_DATA [
        /// 'DAS entropy data.'
        DATA OFFSET(0) NUMBITS(32) [],
    ],
    /// 'RNG status — RN_DATA validity, TRBG/DRBG fault flags, and FIFO/operation indicators.'
    pub STATUS [
        /// 'Set when RN_DATA does NOT contain valid data. Must be 0 before reading RN_DATA in FW mode (otherwise the bus returns SLVERR). In HW mode the read transaction is stretched until data is available.'
        BUSY OFFSET(0) NUMBITS(1) [],
        /// 'TRBG repetition-count health test failed.'
        REPCNT_FAULT_ERROR OFFSET(1) NUMBITS(1) [],
        /// 'TRBG adaptive-proportion health test failed.'
        APT_FAULT_ERROR OFFSET(2) NUMBITS(1) [],
        /// 'TRBG chi-square health test failed.'
        CHISQ_FAULT_ERROR OFFSET(3) NUMBITS(1) [],
        /// 'TRBG internal state-machine fault.'
        RBG_FAULT_ERROR OFFSET(4) NUMBITS(1) [],
        /// 'DRBG anomaly — either an HSSHA fault or an internal DRBG state-machine fault.'
        DRBG_FAULT_ERROR OFFSET(5) NUMBITS(1) [],
        /// 'DRBG instantiate operation in progress.'
        DRBG_INST_BUSY OFFSET(6) NUMBITS(1) [],
        /// 'DRBG reseed operation in progress.'
        DRBG_RESEED_BUSY OFFSET(7) NUMBITS(1) [],
        /// 'Both entropy FIFOs (FIFO1 and EXT_FIFO) are full.'
        ENTROPY_FIFO_FULL OFFSET(8) NUMBITS(1) [],
        /// 'Entropy FIFO read in progress. Cannot switch to FW mode while this is set.'
        ENTROPY_FIFO_READ OFFSET(9) NUMBITS(1) [],
        RSVD_0 OFFSET(10) NUMBITS(22) [],
    ],
    /// 'Programmable DRBG reseed interval (in DRBG generate cycles).'
    pub RESEED_INTERVAL [
        /// 'Reseed interval value.'
        VALUE OFFSET(0) NUMBITS(32) [],
    ],
    /// 'Programmable generate interval — number of generate cycles between K-value updates inside the DRBG.'
    pub GENERATE_INTERVAL [
        /// 'Generate interval value.'
        VALUE OFFSET(0) NUMBITS(10) [],
        RSVD_0 OFFSET(10) NUMBITS(22) [],
    ],
    /// 'Current DRBG reseed counter.'
    pub RESEED_CNT [
        /// 'Reseed counter value.'
        VALUE OFFSET(0) NUMBITS(32) [],
    ],
    /// 'Current DRBG generate counter.'
    pub GENERATE_CNT [
        /// 'Generate counter value.'
        VALUE OFFSET(0) NUMBITS(10) [],
        RSVD_0 OFFSET(10) NUMBITS(22) [],
    ],
    /// 'DRBG state machine status. Encoding: 0=Idle, 1=Instantiate, 2=Generate HMAC Op, 3=Generate Fill FIFO, 4=Generate HMAC Update, 5=Reseed Wait, 6=Reseed, 7=DRBG Error.'
    pub DRBG_STATUS [
        /// 'DRBG state.'
        STATE OFFSET(0) NUMBITS(3) [],
        RSVD_0 OFFSET(3) NUMBITS(29) [],
    ],
    /// 'Upper 2 bits of the TRBG clock divider ratio. Combined with CTRL.CLK_DIV to form {CLK_DIV_MSB[1:0], CTRL.CLK_DIV[7:0], 8'b00} as the divider counter target.'
    pub CLK_DIV_MSB [
        /// 'Clock divider MSB.'
        VALUE OFFSET(0) NUMBITS(2) [],
        RSVD_0 OFFSET(2) NUMBITS(30) [],
    ],
    /// 'Programmable cutoff value for the TRBG repetition-count health test.'
    pub REPCNT_CUTOFF [
        /// 'Repetition-count cutoff.'
        VALUE OFFSET(0) NUMBITS(10) [],
        RSVD_0 OFFSET(10) NUMBITS(22) [],
    ],
    /// 'Programmable cutoff value for the TRBG adaptive-proportion health test.'
    pub APT_CUTOFF [
        /// 'Adaptive-proportion cutoff.'
        VALUE OFFSET(0) NUMBITS(10) [],
        RSVD_0 OFFSET(10) NUMBITS(22) [],
    ],
    /// 'Programmable cutoff value for the TRBG chi-square health test.'
    pub CHISQ_CUTOFF [
        /// 'Chi-square cutoff.'
        VALUE OFFSET(0) NUMBITS(10) [],
        RSVD_0 OFFSET(10) NUMBITS(22) [],
    ],
    /// 'DRBG K state word (RO observation register, 16 banks).'
    pub K [
        /// 'K word.'
        DATA OFFSET(0) NUMBITS(32) [],
    ],
    /// 'DRBG V state word (RO observation register, 16 banks).'
    pub V [
        /// 'V word.'
        DATA OFFSET(0) NUMBITS(32) [],
    ],
    /// 'Random number output. Read consumes one DRBG output word. In HW mode reads stall until data is available; in FW mode STATUS.BUSY must be polled and clear before each read.'
    pub RN_DATA [
        /// 'Random output word.'
        DATA OFFSET(0) NUMBITS(32) [],
    ],
    /// 'FW-mode input FIFO write port. Used to seed the DRBG with test vectors during KAT and ACVP self-testing.'
    pub FWIN_DATA [
        /// 'FW-mode input data.'
        DATA OFFSET(0) NUMBITS(32) [],
    ],
    /// 'FW-mode output FIFO read port. Used to consume DRBG test output during KAT and ACVP self-testing.'
    pub FWOUT_DATA [
        /// 'FW-mode output data.'
        DATA OFFSET(0) NUMBITS(32) [],
    ]
];

pub mod regs {
    //! MMIO register struct for firmware use.
    tock_registers::register_structs! {
        pub RngRegs {
            (0x0 => pub ctrl: crate::RW<u32, super::CTRL::Register>),
            (0x4 => pub das_en: crate::RW<u32, super::DAS_EN::Register>),
            (0x8 => pub das_data: crate::RO<u32, super::DAS_DATA::Register>),
            (0xc => pub status: crate::RO<u32, super::STATUS::Register>),
            (0x10 => pub reseed_interval: crate::RW<u32, super::RESEED_INTERVAL::Register>),
            (0x14 => pub generate_interval: crate::RW<u32, super::GENERATE_INTERVAL::Register>),
            (0x18 => pub reseed_cnt: crate::RO<u32, super::RESEED_CNT::Register>),
            (0x1c => pub generate_cnt: crate::RO<u32, super::GENERATE_CNT::Register>),
            (0x20 => pub drbg_status: crate::RO<u32, super::DRBG_STATUS::Register>),
            (0x24 => pub clk_div_msb: crate::RW<u32, super::CLK_DIV_MSB::Register>),
            (0x28 => _reserved0),
            (0x30 => pub repcnt_cutoff: crate::RW<u32, super::REPCNT_CUTOFF::Register>),
            (0x34 => pub apt_cutoff: crate::RW<u32, super::APT_CUTOFF::Register>),
            (0x38 => pub chisq_cutoff: crate::RW<u32, super::CHISQ_CUTOFF::Register>),
            (0x3c => _reserved1),
            (0x100 => pub k: [crate::RO<u32, super::K::Register>; 16]),
            (0x140 => pub v: [crate::RO<u32, super::V::Register>; 16]),
            (0x180 => _reserved2),
            (0x200 => pub rn_data: crate::RO<u32, super::RN_DATA::Register>),
            (0x204 => _reserved3),
            (0x400 => pub fwin_data: crate::WO<u32, super::FWIN_DATA::Register>),
            (0x404 => _reserved4),
            (0x600 => pub fwout_data: crate::RO<u32, super::FWOUT_DATA::Register>),
            (0x604 => @END),
        }
    }
}
