// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
// AUTO-GENERATED by azihsm_reggen — do not edit.

//! Register definitions for tcon.
//!
//! 'Global timestamp counter + two wakeup timers. uno models only the wakeup1 control path (WAKEUP_CTRL + WAKEUP1_CNT) used to raise `tcon_wakeup1_irq` (NVIC 89) for cross-core crash notification. TSC and wakeup0 are not modeled.  Base address: 0xB000_5000.  Driver uses: WAKEUP_CTRL.WKINTR_LEVEL_EN — wakeup1 level output WAKEUP_CTRL.WKINTR_RPT_EN   — wakeup1 one-shot WAKEUP_CTRL.WAKEUP_ENABLE   — arm/disarm wakeup1 WAKEUP1_CNT                 — fire count'

pub const TCON_BASE: u32 = 0xB0005000;
pub const WAKEUP_CTRL_OFFSET: u32 = 0x10;
pub const WAKEUP1_CNT_OFFSET: u32 = 0x18;

tock_registers::register_bitfields! [u32,
    /// 'Control register for the two wakeup counters. Each field is 2 bits — bit [0] selects wakeup0, bit [1] selects wakeup1 — so writes must preserve the unrelated timer's bit.'
    pub WAKEUP_CTRL [
        /// 'Enable the wakeup counters. [0] enables wakeup0, [1] enables wakeup1. Setting a bit starts that counter counting down from its reload value.'
        WAKEUP_ENABLE OFFSET(0) NUMBITS(2) [],
        RSVD_0 OFFSET(2) NUMBITS(6) [],
        /// 'Interrupt waveform select. 1'b0 = pulse (one 62.5 MHz cycle), 1'b1 = level output held until cleared. [8] for wakeup0, [9] for wakeup1.'
        WKINTR_LEVEL_EN OFFSET(8) NUMBITS(2) [],
        RSVD_1 OFFSET(10) NUMBITS(6) [],
        /// 'Periodic-repeat enable. 1'b1 = the interrupt re-arms periodically, 1'b0 = one-shot. [16] for wakeup0, [17] for wakeup1.'
        WKINTR_RPT_EN OFFSET(16) NUMBITS(2) [],
        RSVD_2 OFFSET(18) NUMBITS(14) [],
    ],
    /// 'Reload / countdown value for the wakeup1 timer. Writing 1 makes wakeup1 expire on the next tick once WAKEUP_ENABLE[1] is set — used to synchronously fire the cross-core crash notification interrupt.'
    pub WAKEUP1_CNT [
        /// 'wakeup1 countdown value.'
        VALUE OFFSET(0) NUMBITS(32) [],
    ]
];

pub mod regs {
    //! MMIO register struct for firmware use.
    tock_registers::register_structs! {
        pub TconRegs {
            (0x0 => _reserved0),
            (0x10 => pub wakeup_ctrl: crate::RW<u32, super::WAKEUP_CTRL::Register>),
            (0x14 => _reserved1),
            (0x18 => pub wakeup1_cnt: crate::RW<u32, super::WAKEUP1_CNT::Register>),
            (0x1c => @END),
        }
    }
}
