// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
// AUTO-GENERATED by azihsm_reggen — do not edit.

//! Register definitions for trace_mailbox.
//!
//! 'Host-firmware trace communication peripheral. Firmware writes task ID and IRQ state via volatile stores; a host-side tracer reads them for per-task instruction profiling.'

pub const TRACE_MAILBOX_BASE: u32 = 0x40002000;
pub const TASK_ID_OFFSET: u32 = 0x00;
pub const EVENT_OFFSET: u32 = 0x04;
pub const BEGIN_COUNT_OFFSET: u32 = 0x08;
pub const IRQ_NUM_OFFSET: u32 = 0x0C;
pub const LAST_BEGIN_TASK_OFFSET: u32 = 0x10;

tock_registers::register_bitfields! [u32,
    /// 'Current Embassy task ID. Written by firmware trace hooks. 0 = no task active (executor overhead or IRQ handler). Non-zero = address of the active TaskHeader struct.'
    pub TASK_ID [
        TASK_ID OFFSET(0) NUMBITS(32) [],
    ],
    /// 'Last trace event type. Written by firmware trace hooks. 1 = task_exec_begin 2 = task_exec_end 3 = task_new 4 = task_complete'
    pub EVENT [
        EVENT OFFSET(0) NUMBITS(32) [],
    ],
    /// 'Total number of task_exec_begin events since boot. Incremented by firmware on each task poll. Used by the host tracer to detect new poll cycles.'
    pub BEGIN_COUNT [
        BEGIN_COUNT OFFSET(0) NUMBITS(32) [],
    ],
    /// 'Active exception number (IPSR value). Written by the interrupt handler on entry, cleared on exit. 0 = thread mode (no active exception). 16 = IRQ0, 17 = IRQ1, etc.'
    pub IRQ_NUM [
        IRQ_NUM OFFSET(0) NUMBITS(32) [],
    ],
    /// 'Task ID of the most recent task_exec_begin event. Written atomically with begin_count by the firmware trace hooks. The host tracer uses this to attribute each begin_count delta to the correct task, even when task_begin+task_end happen within a single basic block.'
    pub LAST_BEGIN_TASK [
        TASK_ID OFFSET(0) NUMBITS(32) [],
    ]
];

pub mod regs {
    //! MMIO register struct for firmware use.
    tock_registers::register_structs! {
        pub TraceMailboxRegs {
            (0x0 => pub task_id: crate::RW<u32, super::TASK_ID::Register>),
            (0x4 => pub event: crate::RW<u32, super::EVENT::Register>),
            (0x8 => pub begin_count: crate::RW<u32, super::BEGIN_COUNT::Register>),
            (0xc => pub irq_num: crate::RW<u32, super::IRQ_NUM::Register>),
            (0x10 => pub last_begin_task: crate::RW<u32, super::LAST_BEGIN_TASK::Register>),
            (0x14 => @END),
        }
    }
}
