// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
// AUTO-GENERATED by azihsm_reggen — do not edit.

//! Register definitions for uart.
//!
//! 'UART registers used by the HSM driver.  Base address: 0xB000_9000  Driver uses: RX_BUF.DATA       — read received byte STATUS.RX_READY   — poll before reading TX_HOLD.DATA      — write byte to transmit STATUS.TX_READY   — poll before writing'

pub const UART_BASE: u32 = 0xB0009000;
pub const RX_BUF_OFFSET: u32 = 0x00;
pub const TX_HOLD_OFFSET: u32 = 0x04;
pub const STATUS_OFFSET: u32 = 0x0C;

tock_registers::register_bitfields! [u32,
    /// 'RX data register. Read when RX_READY is set. Reading also clears the RX_READY status bit.'
    pub RX_BUF [
        /// 'Received data byte.'
        DATA OFFSET(0) NUMBITS(8) [],
        RSVD_1 OFFSET(8) NUMBITS(4) [],
        /// 'Overrun error mirror (when st_mirror_en=1).'
        OVRUN_ERR_MIRR OFFSET(12) NUMBITS(1) [],
        /// 'Parity error detect mirror (when st_mirror_en=1).'
        PARITY_ERR_DET OFFSET(13) NUMBITS(1) [],
        /// 'Frame error detect mirror (when st_mirror_en=1).'
        FRAME_ERR_DET OFFSET(14) NUMBITS(1) [],
        /// 'Break detect mirror (when st_mirror_en=1).'
        BREAK_DET OFFSET(15) NUMBITS(1) [],
        RSVD_0 OFFSET(16) NUMBITS(16) [],
    ],
    /// 'TX data register. Write when TX_READY is set. Writing clears the TX_READY status bit.'
    pub TX_HOLD [
        /// 'Byte to transmit.'
        DATA OFFSET(0) NUMBITS(8) [],
        RSVD_0 OFFSET(8) NUMBITS(24) [],
    ],
    /// 'UART status — TX/RX ready, FIFO, and error flags.'
    pub STATUS [
        /// 'Overrun error. Cleared on RX buffer read.'
        OVRUN_ERR OFFSET(0) NUMBITS(1) [],
        /// 'Parity error. Cleared on RX buffer read.'
        PARITY_ERR OFFSET(1) NUMBITS(1) [],
        /// 'Frame error. Cleared on RX buffer read.'
        FRAME_ERR OFFSET(2) NUMBITS(1) [],
        /// 'Break sequence detected.'
        BREAK_DET OFFSET(3) NUMBITS(1) [],
        /// 'RX ready — new byte available in RX buffer.'
        RX_READY OFFSET(4) NUMBITS(1) [],
        /// 'TX ready — TX holding register empty.'
        TX_READY OFFSET(5) NUMBITS(1) [],
        /// 'TX empty — holding register and shift register both empty.'
        TX_EMPTY OFFSET(6) NUMBITS(1) [],
        RXFIFO_HFULL OFFSET(7) NUMBITS(1) [],
        RXFIFO_FULL OFFSET(8) NUMBITS(1) [],
        /// 'RX toggle — write 1 to clear.'
        RX_TOGGLE OFFSET(9) NUMBITS(1) [],
        TXFIFO_HFULL OFFSET(10) NUMBITS(1) [],
        TXFIFO_FULL OFFSET(11) NUMBITS(1) [],
        RXFIFO_EMPTY OFFSET(12) NUMBITS(1) [],
        TXFIFO_EMPTY OFFSET(13) NUMBITS(1) [],
        RSVD_1 OFFSET(14) NUMBITS(4) [],
        RTSN_THRESHOLD_MET OFFSET(18) NUMBITS(1) [],
        RSVD_0 OFFSET(19) NUMBITS(2) [],
        RTSN_O OFFSET(21) NUMBITS(1) [],
        CTSN_I OFFSET(22) NUMBITS(1) [],
        RSVD_TOP OFFSET(23) NUMBITS(9) [],
    ]
];

pub mod regs {
    //! MMIO register struct for firmware use.
    tock_registers::register_structs! {
        pub UartRegs {
            (0x0 => pub rx_buf: crate::RO<u32, super::RX_BUF::Register>),
            (0x4 => pub tx_hold: crate::WO<u32, super::TX_HOLD::Register>),
            (0x8 => _reserved0),
            (0xc => pub status: crate::RW<u32, super::STATUS::Register>),
            (0x10 => @END),
        }
    }
}
