// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
// AUTO-GENERATED by azihsm_reggen — do not edit.

//! Register definitions for upka.
//!
//! 'Unified Public Key Accelerator — 16-engine pool. Each engine instance is a self-contained ECC / RSA / modular-arithmetic processor with its own descriptor doorbell, status, and IRQ pair (Done / Error). Base address 0xC000_0000.'

pub const UPKA_BASE: u32 = 0xC0000000;
pub const ENGINE_OFFSET: u32 = 0x00;
pub const ENGINE_COUNT: u32 = 16;
pub const ENGINE_STRIDE: u32 = 0x1000;

tock_registers::register_bitfields! [u32,
    /// 'Engine status. Polled by firmware between submit and completion; latched by the engine on every state transition. A Done or Error IRQ fires on every command completion (positive and negative).'
    pub UPKA_ENGINE_STATUS [
        /// 'Engine is currently processing a command. Cleared on completion (success or error). Firmware must NOT write the COMMAND register while BUSY is set.'
        BUSY OFFSET(0) NUMBITS(1) [],
        /// 'Engine successfully finished the most recent command. Mutually exclusive with the ERROR_* bits.'
        COMPLETE OFFSET(1) NUMBITS(1) [],
        /// 'Engine could not decode the command structure successfully (invalid opcode, bad descriptor layout).'
        ERROR_CMD OFFSET(2) NUMBITS(1) [],
        /// 'Engine encountered an error initiating a bus transaction (e.g. SLVERR / DECERR on a result, arg, or descriptor fetch).'
        ERROR_BUS OFFSET(3) NUMBITS(1) [],
        /// 'Engine detected an internal fault while working on the operation (parity, lane-fault, or engine-fault).'
        ERROR_FAULT OFFSET(4) NUMBITS(1) [],
        /// 'Engine is/was working on a command initiated by a different bus master than the one reading the STATUS register. Driver masks this bit out of completion decode.'
        NOT_OWNER OFFSET(5) NUMBITS(1) [],
        RSVD_0 OFFSET(6) NUMBITS(26) [],
    ]
];

/// Regfile entry struct for `upka_engine`.
#[repr(C)]
pub struct UpkaEngine {
    pub command: crate::RW<u32>,
    pub status: crate::RO<u32, UPKA_ENGINE_STATUS::Register>,
    pub ecc_count: crate::RO<u32>,
    _pad0: [u32; 1021],
}

pub mod regs {
    //! MMIO register struct for firmware use.
    tock_registers::register_structs! {
        pub UpkaRegs {
            (0x0 => pub engine: [super::UpkaEngine; 16]),
            (0x10000 => @END),
        }
    }
}
