// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
// AUTO-GENERATED by azihsm_reggen — do not edit.

#![no_std]
#![allow(clippy::modulo_one)]

/// Register access type aliases.
///
/// With the `emu` feature enabled (used by the emulator's device crate),
/// all register types become `ReadWrite` so the emulator can read and
/// write all registers through the backing store. Without the feature,
/// registers use their correct access types (`ReadOnly`, `WriteOnly`).
#[cfg(feature = "emu")]
mod access {
    pub type RW<T, R = ()> = tock_registers::registers::ReadWrite<T, R>;
    pub type RO<T, R = ()> = tock_registers::registers::ReadWrite<T, R>;
    pub type WO<T, R = ()> = tock_registers::registers::ReadWrite<T, R>;
}

#[cfg(not(feature = "emu"))]
mod access {
    pub type RW<T, R = ()> = tock_registers::registers::ReadWrite<T, R>;
    pub type RO<T, R = ()> = tock_registers::registers::ReadOnly<T, R>;
    pub type WO<T, R = ()> = tock_registers::registers::WriteOnly<T, R>;
}

pub use access::*;
pub mod nvic;
pub mod scb;
pub mod systick;
pub mod tcm;
