// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
// AUTO-GENERATED by azihsm_reggen — do not edit.

//! Register definitions for nvic.
//!
//! 'ARMv7-M Nested Vectored Interrupt Controller. Supports up to 240 external interrupts with 8-bit priority. Array sizes: 8 registers cover 256 interrupts (ISERn, etc.), 60 IPR registers cover 240 interrupt priorities.'

pub const NVIC_BASE: u32 = 0xE000E100;
pub const ISER_OFFSET: u32 = 0x00;
pub const ICER_OFFSET: u32 = 0x80;
pub const ISPR_OFFSET: u32 = 0x100;
pub const ICPR_OFFSET: u32 = 0x180;
pub const IABR_OFFSET: u32 = 0x200;
pub const IPR_OFFSET: u32 = 0x300;
pub const STIR_OFFSET: u32 = 0xE00;

tock_registers::register_bitfields! [u32,
    /// '32-bit register where each bit corresponds to one interrupt. For ISERn, bit m controls interrupt (32n + m). ISER/ISPR: write-1-to-set. ICER/ICPR: write-1-to-clear. IABR: read-only active bits.'
    pub ISER [
        BITS OFFSET(0) NUMBITS(32) [],
    ],
    /// '32-bit register where each bit corresponds to one interrupt. For ISERn, bit m controls interrupt (32n + m). ISER/ISPR: write-1-to-set. ICER/ICPR: write-1-to-clear. IABR: read-only active bits.'
    pub ICER [
        BITS OFFSET(0) NUMBITS(32) [],
    ],
    /// '32-bit register where each bit corresponds to one interrupt. For ISERn, bit m controls interrupt (32n + m). ISER/ISPR: write-1-to-set. ICER/ICPR: write-1-to-clear. IABR: read-only active bits.'
    pub ISPR [
        BITS OFFSET(0) NUMBITS(32) [],
    ],
    /// '32-bit register where each bit corresponds to one interrupt. For ISERn, bit m controls interrupt (32n + m). ISER/ISPR: write-1-to-set. ICER/ICPR: write-1-to-clear. IABR: read-only active bits.'
    pub ICPR [
        BITS OFFSET(0) NUMBITS(32) [],
    ],
    /// 'Read-only. Each bit indicates whether the corresponding interrupt is active.'
    pub IABR [
        BITS OFFSET(0) NUMBITS(32) [],
    ],
    /// 'Contains 4 packed 8-bit priority fields. Only upper bits (implementation-defined, typically bits[7:4]) are used.'
    pub IPR [
        PRI_0 OFFSET(0) NUMBITS(8) [],
        PRI_1 OFFSET(8) NUMBITS(8) [],
        PRI_2 OFFSET(16) NUMBITS(8) [],
        PRI_3 OFFSET(24) NUMBITS(8) [],
    ],
    /// 'Write-only. Triggers the specified interrupt.'
    pub STIR [
        INTID OFFSET(0) NUMBITS(9) [],
    ]
];

pub mod regs {
    //! MMIO register struct for firmware use.
    tock_registers::register_structs! {
        pub NvicRegs {
            (0x0 => pub iser: [crate::RW<u32, super::ISER::Register>; 8]),
            (0x20 => _reserved0),
            (0x80 => pub icer: [crate::RW<u32, super::ICER::Register>; 8]),
            (0xa0 => _reserved1),
            (0x100 => pub ispr: [crate::RW<u32, super::ISPR::Register>; 8]),
            (0x120 => _reserved2),
            (0x180 => pub icpr: [crate::RW<u32, super::ICPR::Register>; 8]),
            (0x1a0 => _reserved3),
            (0x200 => pub iabr: [crate::RO<u32, super::IABR::Register>; 8]),
            (0x220 => _reserved4),
            (0x300 => pub ipr: [crate::RW<u32, super::IPR::Register>; 60]),
            (0x3f0 => _reserved5),
            (0xe00 => pub stir: crate::RW<u32, super::STIR::Register>),
            (0xe04 => @END),
        }
    }
}
