// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
// AUTO-GENERATED by azihsm_reggen — do not edit.

//! Register definitions for scb.
//!
//! 'ARMv7-M System Control Block. Provides system-level configuration including interrupt control, fault status, and reset management.'

pub const SCB_BASE: u32 = 0xE000ED00;
pub const CPUID_OFFSET: u32 = 0x00;
pub const ICSR_OFFSET: u32 = 0x04;
pub const VTOR_OFFSET: u32 = 0x08;
pub const AIRCR_OFFSET: u32 = 0x0C;
pub const SCR_OFFSET: u32 = 0x10;
pub const CCR_OFFSET: u32 = 0x14;
pub const SHPR1_OFFSET: u32 = 0x18;
pub const SHPR2_OFFSET: u32 = 0x1C;
pub const SHPR3_OFFSET: u32 = 0x20;
pub const SHCSR_OFFSET: u32 = 0x24;
pub const CFSR_OFFSET: u32 = 0x28;
pub const HFSR_OFFSET: u32 = 0x2C;
pub const DFSR_OFFSET: u32 = 0x30;
pub const MMFAR_OFFSET: u32 = 0x34;
pub const BFAR_OFFSET: u32 = 0x38;
pub const AFSR_OFFSET: u32 = 0x3C;

tock_registers::register_bitfields! [u32,
    /// 'Read-only. Contains processor identification.'
    pub CPUID [
        REVISION OFFSET(0) NUMBITS(4) [],
        PARTNO OFFSET(4) NUMBITS(12) [],
        ARCHITECTURE OFFSET(16) NUMBITS(4) [],
        VARIANT OFFSET(20) NUMBITS(4) [],
        IMPLEMENTER OFFSET(24) NUMBITS(8) [],
    ],
    /// 'Provides NMI, PendSV, SysTick control and pending/active status.'
    pub ICSR [
        VECTACTIVE OFFSET(0) NUMBITS(9) [],
        RETTOBASE OFFSET(11) NUMBITS(1) [],
        VECTPENDING OFFSET(12) NUMBITS(9) [],
        ISRPENDING OFFSET(22) NUMBITS(1) [],
        PENDSTCLR OFFSET(25) NUMBITS(1) [],
        PENDSTSET OFFSET(26) NUMBITS(1) [],
        PENDSVCLR OFFSET(27) NUMBITS(1) [],
        PENDSVSET OFFSET(28) NUMBITS(1) [],
        NMIPENDSET OFFSET(31) NUMBITS(1) [],
    ],
    /// 'Holds the vector table base address.'
    pub VTOR [
        TBLOFF OFFSET(7) NUMBITS(25) [],
    ],
    /// 'Controls reset behavior, endianness, and priority grouping. Writes require VECTKEY = 0x05FA in bits[31:16].'
    pub AIRCR [
        VECTRESET OFFSET(0) NUMBITS(1) [],
        VECTCLRACTIVE OFFSET(1) NUMBITS(1) [],
        SYSRESETREQ OFFSET(2) NUMBITS(1) [],
        PRIGROUP OFFSET(8) NUMBITS(3) [],
        ENDIANNESS OFFSET(15) NUMBITS(1) [],
        VECTKEY OFFSET(16) NUMBITS(16) [],
    ],
    /// 'Controls sleep behavior.'
    pub SCR [
        SLEEPONEXIT OFFSET(1) NUMBITS(1) [],
        SLEEPDEEP OFFSET(2) NUMBITS(1) [],
        SEVONPEND OFFSET(4) NUMBITS(1) [],
    ],
    /// 'Controls trap behavior, stack alignment, and caches.'
    pub CCR [
        NONBASETHRDENA OFFSET(0) NUMBITS(1) [],
        USERSETMPEND OFFSET(1) NUMBITS(1) [],
        UNALIGN_TRP OFFSET(3) NUMBITS(1) [],
        DIV_0_TRP OFFSET(4) NUMBITS(1) [],
        BFHFNMIGN OFFSET(8) NUMBITS(1) [],
        STKALIGN OFFSET(9) NUMBITS(1) [],
        DC OFFSET(16) NUMBITS(1) [],
        IC OFFSET(17) NUMBITS(1) [],
        BP OFFSET(18) NUMBITS(1) [],
    ],
    /// 'Configures priority of system handlers. Contains 4 packed 8-bit priority fields. Only upper 4 bits of each are used.'
    pub SHPR1 [
        PRI_0 OFFSET(0) NUMBITS(8) [],
        PRI_1 OFFSET(8) NUMBITS(8) [],
        PRI_2 OFFSET(16) NUMBITS(8) [],
        PRI_3 OFFSET(24) NUMBITS(8) [],
    ],
    /// 'Configures priority of system handlers. Contains 4 packed 8-bit priority fields. Only upper 4 bits of each are used.'
    pub SHPR2 [
        PRI_0 OFFSET(0) NUMBITS(8) [],
        PRI_1 OFFSET(8) NUMBITS(8) [],
        PRI_2 OFFSET(16) NUMBITS(8) [],
        PRI_3 OFFSET(24) NUMBITS(8) [],
    ],
    /// 'Configures priority of system handlers. Contains 4 packed 8-bit priority fields. Only upper 4 bits of each are used.'
    pub SHPR3 [
        PRI_0 OFFSET(0) NUMBITS(8) [],
        PRI_1 OFFSET(8) NUMBITS(8) [],
        PRI_2 OFFSET(16) NUMBITS(8) [],
        PRI_3 OFFSET(24) NUMBITS(8) [],
    ],
    /// 'Controls fault handler enable and active/pending status.'
    pub SHCSR [
        MEMFAULTACT OFFSET(0) NUMBITS(1) [],
        BUSFAULTACT OFFSET(1) NUMBITS(1) [],
        USGFAULTACT OFFSET(3) NUMBITS(1) [],
        SVCALLACT OFFSET(7) NUMBITS(1) [],
        MONITORACT OFFSET(8) NUMBITS(1) [],
        PENDSVACT OFFSET(10) NUMBITS(1) [],
        SYSTICKACT OFFSET(11) NUMBITS(1) [],
        USGFAULTPENDED OFFSET(12) NUMBITS(1) [],
        MEMFAULTPENDED OFFSET(13) NUMBITS(1) [],
        BUSFAULTPENDED OFFSET(14) NUMBITS(1) [],
        SVCALLPENDED OFFSET(15) NUMBITS(1) [],
        MEMFAULTENA OFFSET(16) NUMBITS(1) [],
        BUSFAULTENA OFFSET(17) NUMBITS(1) [],
        USGFAULTENA OFFSET(18) NUMBITS(1) [],
    ],
    /// 'Combined MMFSR[7:0] + BFSR[15:8] + UFSR[31:16]. Write-1-to-clear.'
    pub CFSR [
        IACCVIOL OFFSET(0) NUMBITS(1) [],
        DACCVIOL OFFSET(1) NUMBITS(1) [],
        MUNSTKERR OFFSET(3) NUMBITS(1) [],
        MSTKERR OFFSET(4) NUMBITS(1) [],
        MLSPERR OFFSET(5) NUMBITS(1) [],
        MMARVALID OFFSET(7) NUMBITS(1) [],
        IBUSERR OFFSET(8) NUMBITS(1) [],
        PRECISERR OFFSET(9) NUMBITS(1) [],
        IMPRECISERR OFFSET(10) NUMBITS(1) [],
        UNSTKERR OFFSET(11) NUMBITS(1) [],
        STKERR OFFSET(12) NUMBITS(1) [],
        LSPERR OFFSET(13) NUMBITS(1) [],
        BFARVALID OFFSET(15) NUMBITS(1) [],
        UNDEFINSTR OFFSET(16) NUMBITS(1) [],
        INVSTATE OFFSET(17) NUMBITS(1) [],
        INVPC OFFSET(18) NUMBITS(1) [],
        NOCP OFFSET(19) NUMBITS(1) [],
        UNALIGNED OFFSET(24) NUMBITS(1) [],
        DIVBYZERO OFFSET(25) NUMBITS(1) [],
    ],
    /// 'Indicates cause of HardFault. Write-1-to-clear.'
    pub HFSR [
        VECTTBL OFFSET(1) NUMBITS(1) [],
        FORCED OFFSET(30) NUMBITS(1) [],
        DEBUGEVT OFFSET(31) NUMBITS(1) [],
    ],
    /// 'Indicates cause of debug event. Write-1-to-clear.'
    pub DFSR [
        HALTED OFFSET(0) NUMBITS(1) [],
        BKPT OFFSET(1) NUMBITS(1) [],
        DWTTRAP OFFSET(2) NUMBITS(1) [],
        VCATCH OFFSET(3) NUMBITS(1) [],
        EXTERNAL OFFSET(4) NUMBITS(1) [],
    ],
    /// 'Holds 32-bit fault address.'
    pub MMFAR [
        ADDRESS OFFSET(0) NUMBITS(32) [],
    ],
    /// 'Holds 32-bit fault address.'
    pub BFAR [
        ADDRESS OFFSET(0) NUMBITS(32) [],
    ],
    /// 'Implementation-defined auxiliary fault information.'
    pub AFSR [
        AUXFAULT OFFSET(0) NUMBITS(32) [],
    ]
];

pub mod regs {
    //! MMIO register struct for firmware use.
    tock_registers::register_structs! {
        pub ScbRegs {
            (0x0 => pub cpuid: crate::RO<u32, super::CPUID::Register>),
            (0x4 => pub icsr: crate::RW<u32, super::ICSR::Register>),
            (0x8 => pub vtor: crate::RW<u32, super::VTOR::Register>),
            (0xc => pub aircr: crate::RW<u32, super::AIRCR::Register>),
            (0x10 => pub scr: crate::RW<u32, super::SCR::Register>),
            (0x14 => pub ccr: crate::RW<u32, super::CCR::Register>),
            (0x18 => pub shpr1: crate::RW<u32, super::SHPR1::Register>),
            (0x1c => pub shpr2: crate::RW<u32, super::SHPR2::Register>),
            (0x20 => pub shpr3: crate::RW<u32, super::SHPR3::Register>),
            (0x24 => pub shcsr: crate::RW<u32, super::SHCSR::Register>),
            (0x28 => pub cfsr: crate::RW<u32, super::CFSR::Register>),
            (0x2c => pub hfsr: crate::RW<u32, super::HFSR::Register>),
            (0x30 => pub dfsr: crate::RW<u32, super::DFSR::Register>),
            (0x34 => pub mmfar: crate::RW<u32, super::MMFAR::Register>),
            (0x38 => pub bfar: crate::RW<u32, super::BFAR::Register>),
            (0x3c => pub afsr: crate::RW<u32, super::AFSR::Register>),
            (0x40 => @END),
        }
    }
}
