// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
// AUTO-GENERATED by azihsm_reggen — do not edit.

//! Register definitions for systick.
//!
//! 'ARMv7-M System Timer. Decrementing 24-bit counter with auto-reload from RVR. Optionally generates SysTick exception.'

pub const SYSTICK_BASE: u32 = 0xE000E010;
pub const CSR_OFFSET: u32 = 0x00;
pub const RVR_OFFSET: u32 = 0x04;
pub const CVR_OFFSET: u32 = 0x08;
pub const CALIB_OFFSET: u32 = 0x0C;

tock_registers::register_bitfields! [u32,
    /// 'Controls the SysTick timer and provides status.'
    pub CSR [
        ENABLE OFFSET(0) NUMBITS(1) [],
        TICKINT OFFSET(1) NUMBITS(1) [],
        CLKSOURCE OFFSET(2) NUMBITS(1) [],
        COUNTFLAG OFFSET(16) NUMBITS(1) [],
    ],
    /// 'Reload value for the counter on wrap to zero.'
    pub RVR [
        RELOAD OFFSET(0) NUMBITS(24) [],
    ],
    /// 'Current counter value. Any write clears to zero and clears COUNTFLAG.'
    pub CVR [
        CURRENT OFFSET(0) NUMBITS(32) [],
    ],
    /// 'Calibration and implementation information.'
    pub CALIB [
        TENMS OFFSET(0) NUMBITS(24) [],
        SKEW OFFSET(30) NUMBITS(1) [],
        NOREF OFFSET(31) NUMBITS(1) [],
    ]
];

pub mod regs {
    //! MMIO register struct for firmware use.
    tock_registers::register_structs! {
        pub SystickRegs {
            (0x0 => pub csr: crate::RW<u32, super::CSR::Register>),
            (0x4 => pub rvr: crate::RW<u32, super::RVR::Register>),
            (0x8 => pub cvr: crate::RW<u32, super::CVR::Register>),
            (0xc => pub calib: crate::RO<u32, super::CALIB::Register>),
            (0x10 => @END),
        }
    }
}
