// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
// AUTO-GENERATED by azihsm_reggen — do not edit.

//! Register definitions for tcm.
//!
//! 'Cortex-M7 Tightly-Coupled Memory control registers. ITCMCR and DTCMCR share the same register layout.'

pub const TCM_BASE: u32 = 0xE000EF90;
pub const ITCMCR_OFFSET: u32 = 0x00;
pub const DTCMCR_OFFSET: u32 = 0x04;

tock_registers::register_bitfields! [u32,
    /// 'Controls TCM enable, read-modify-write, and retry behavior. SZ field is read-only (set by implementation configuration).'
    pub ITCMCR [
        EN OFFSET(0) NUMBITS(1) [],
        RMW OFFSET(1) NUMBITS(1) [],
        RETEN OFFSET(2) NUMBITS(1) [],
        SZ OFFSET(3) NUMBITS(4) [],
    ],
    /// 'Controls TCM enable, read-modify-write, and retry behavior. SZ field is read-only (set by implementation configuration).'
    pub DTCMCR [
        EN OFFSET(0) NUMBITS(1) [],
        RMW OFFSET(1) NUMBITS(1) [],
        RETEN OFFSET(2) NUMBITS(1) [],
        SZ OFFSET(3) NUMBITS(4) [],
    ]
];

pub mod regs {
    //! MMIO register struct for firmware use.
    tock_registers::register_structs! {
        pub TcmRegs {
            (0x0 => pub itcmcr: crate::RW<u32, super::ITCMCR::Register>),
            (0x4 => pub dtcmcr: crate::RW<u32, super::DTCMCR::Register>),
            (0x8 => @END),
        }
    }
}
