// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! X.509 certificate and CSR builder for AZIHSM.
//!
//! This crate provides runtime certificate and CSR construction from
//! pre-generated DER TBS (To-Be-Signed) templates. The approach is inspired
//! by Caliptra's x509 crate: a generator tool (Linux-only, OpenSSL-based)
//! creates valid certificates with known placeholder byte patterns, then the
//! runtime code patches variable fields at known offsets and assembles the
//! final DER-encoded certificate with an ECDSA-P384 signature.
//!
//! # Architecture
//!
//! - **Templates** (`root_cert`, `intermediate_cert`, `leaf_cert`, `device_csr`):
//!   Auto-generated Rust modules containing `const` TBS byte arrays with
//!   placeholder bytes (`0x5F`) at variable field positions, plus `const`
//!   offset/length values for each field.
//!
//! - **Builders** (`cert_builder`, `csr_builder`): Runtime functions that
//!   copy a TBS template, patch variable fields (public key, serial number,
//!   CN, SN, validity dates, extensions), encode the caller-provided ECDSA-384
//!   signature in DER, and assemble the complete certificate or CSR.
//!
//! - **DER helpers** (`der_helpers`): Low-level DER encoding routines for
//!   length fields, integers, and ECDSA signatures.
//!
//! # Template Generation
//!
//! Templates are generated by the `azihsm_fw_hsm_std_x509_gen` tool
//! (`cargo run -p azihsm_fw_hsm_std_x509_gen`). That tool only builds on
//! Linux and requires OpenSSL. Regenerate templates after changing field
//! sizes or certificate structure.
//!
//! # Supported Certificate Types
//!
//! | Type | Module | Extensions |
//! |------|--------|------------|
//! | Root CA (self-signed) | [`root_cert`] | BasicConstraints(CA:TRUE), KeyUsage(keyCertSign+cRLSign), SKI |
//! | Intermediate CA | [`intermediate_cert`] | BasicConstraints(CA:TRUE, pathlen), KeyUsage(keyCertSign+cRLSign), SKI, AKI |
//! | Leaf (end-entity) | [`leaf_cert`] | BasicConstraints(CA:FALSE), KeyUsage(variable), SKI, AKI |
//! | Device CSR (PKCS#10) | [`device_csr`] | Subject DN only (CN + serialNumber) |

/// Runtime certificate builder for Root CA, Intermediate CA, and Leaf certificates.
pub mod cert_builder;

/// Runtime CSR (PKCS#10 CertificationRequest) builder.
pub mod csr_builder;

/// Low-level DER encoding helpers for ECDSA signatures and length fields.
pub mod der_helpers;

// Auto-generated template modules (regenerated by `azihsm_fw_hsm_std_x509_gen`).

/// Device CSR (PKCS#10) TBS template — auto-generated.
pub mod device_csr;

/// Intermediate CA certificate TBS template — auto-generated.
pub mod intermediate_cert;

/// Leaf (end-entity) certificate TBS template — auto-generated.
pub mod leaf_cert;

/// Root CA (self-signed) certificate TBS template — auto-generated.
pub mod root_cert;
