// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! Generate trait-based BusDevice peripheral implementations from a
//! [`SocSchema`](crate::schema::SocSchema).
//!
//! For each peripheral, generates:
//! - `Xxx` — trait with `reg()` + per-register `read_/write_` default impls
//! - `XxxDevice<T>` — generic `BusDevice` adapter with backing store
//!
//! Register storage lives in the device's backing store (`Box<[u8]>`),
//! reinterpreted as the MMIO struct from the `regs` crate. This means
//! the same memory backs both emulator register access and tlib's
//! guest→host pointer mapping.

use proc_macro2::Ident;
use proc_macro2::Span;
use proc_macro2::TokenStream;
use quote::format_ident;
use quote::quote;

use crate::schema::BlockItem;
use crate::schema::FieldAccess;
use crate::schema::Register;
use crate::schema::RegisterBlock;
use crate::schema::SocSchema;

/// Create an identifier, using raw identifier syntax (`r#`) for Rust keywords.
fn make_ident(name: &str) -> Ident {
    const KEYWORDS: &[&str] = &[
        "as", "break", "const", "continue", "crate", "else", "enum", "extern", "false", "fn",
        "for", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub", "ref",
        "return", "self", "static", "struct", "super", "trait", "true", "type", "unsafe", "use",
        "where", "while", "async", "await", "dyn", "abstract", "become", "box", "do", "final",
        "macro", "override", "priv", "typeof", "unsized", "virtual", "yield", "try",
    ];
    if KEYWORDS.contains(&name) {
        Ident::new_raw(name, Span::call_site())
    } else {
        Ident::new(name, Span::call_site())
    }
}

const HEADER: &str = "\
    // Copyright (c) Microsoft Corporation.\n\
    // Licensed under the MIT License.\n\
    // AUTO-GENERATED by azihsm_reggen — do not edit.\n";

/// Generate peripheral code for a single register block.
///
/// `soc_name` is used to derive the fw_regs crate name
/// (e.g. the regs crate name for the target).
pub fn generate_block(block: &RegisterBlock, regs_crate: &str, bus_crate: &str) -> String {
    let pascal = to_pascal_case(&block.name);
    let regs_struct_name = format_ident!("{}Regs", pascal);
    let trait_name = format_ident!("{}", pascal);
    let device_name = format_ident!("{}Device", pascal);
    let upper_name = block.name.to_uppercase();

    // Header (raw string — quote can't generate comments)
    let mut header = format!("{}\n//! Emulator peripheral for {}.\n", HEADER, block.name);
    if !crate::sanitize_desc(&block.desc).is_empty() {
        header.push_str(&format!("//!\n//! {}\n", crate::sanitize_desc(&block.desc)));
    }
    header.push('\n');

    // Imports and constants
    let fw_regs_crate = format_ident!("{}", regs_crate);
    let bus_crate_ident = format_ident!("{}", bus_crate);
    let periph_mod = format_ident!("{}", block.name);
    let base_ident = format_ident!("{}_BASE", upper_name);
    let size_ident = format_ident!("{}_SIZE", upper_name);
    let base_lit = syn::LitInt::new(&format!("0x{:08X}", block.base_addr), Span::call_site());
    let computed_size = compute_block_size(block);
    let size_lit = syn::LitInt::new(&format!("0x{:X}", computed_size), Span::call_site());

    let imports_and_consts = quote! {
        use #bus_crate_ident::{BusDevice, BusError};
        #[allow(unused_imports)]
        use #fw_regs_crate::#periph_mod::*;
        #[allow(unused_imports)]
        use tock_registers::interfaces::{Readable, Writeable};

        pub use #fw_regs_crate::#periph_mod::regs::#regs_struct_name;

        pub const #base_ident: u32 = #base_lit;
        pub const #size_ident: u32 = #size_lit;
    };

    // ── Xxx trait ───────────────────────────────────────────────────
    let mut trait_methods = Vec::<TokenStream>::new();
    let mut trait_comments: Vec<(String, String)> = Vec::new();

    for reg in block.registers() {
        let field_name = make_ident(&reg.name.to_lowercase());
        let read_fn = format_ident!("read_{}", reg.name.to_lowercase());
        let write_fn = format_ident!("write_{}", reg.name.to_lowercase());

        if let Some(count) = reg.count {
            // Array register — methods take an index parameter
            let count_lit = syn::LitInt::new(&format!("{}", count), Span::call_site());
            trait_methods.push(quote! {
                fn #read_fn(&self, idx: usize) -> u32 {
                    assert!(idx < #count_lit);
                    self.reg().#field_name[idx].get()
                }
            });
            trait_methods.push(quote! {
                fn #write_fn(&mut self, idx: usize, val: u32) {
                    assert!(idx < #count_lit);
                    self.reg().#field_name[idx].set(val);
                }
            });
        } else {
            // Scalar register — read method returns via .get()
            trait_methods.push(quote! {
                fn #read_fn(&self) -> u32 {
                    self.reg().#field_name.get()
                }
            });

            // write method — depends on access type
            let all_ro = reg.fields.iter().all(|f| f.access == FieldAccess::RO);
            let all_w1c = reg.fields.iter().all(|f| f.access == FieldAccess::W1C);
            let all_w1s = reg.fields.iter().all(|f| f.access == FieldAccess::W1S);
            let field_name_str = reg.name.to_lowercase();

            if all_ro {
                // RO: write is a no-op
                trait_comments.push((
                    format!("fn write_{}(&mut self, _val: u32) {{}}", field_name_str),
                    format!(
                        "fn write_{}(&mut self, _val: u32) {{}} // RO",
                        field_name_str
                    ),
                ));
                trait_methods.push(quote! {
                    fn #write_fn(&mut self, _val: u32) {}
                });
            } else if all_w1c {
                // W1C: read-modify-write to clear bits
                trait_comments.push((
                    format!("self.reg().{}.set(cur & !val);", field_name_str),
                    format!("self.reg().{}.set(cur & !val); // W1C", field_name_str),
                ));
                trait_methods.push(quote! {
                    fn #write_fn(&mut self, val: u32) {
                        let cur = self.reg().#field_name.get();
                        self.reg().#field_name.set(cur & !val);
                    }
                });
            } else if all_w1s {
                // W1S: read-modify-write to set bits
                trait_comments.push((
                    format!("self.reg().{}.set(cur | val);", field_name_str),
                    format!("self.reg().{}.set(cur | val); // W1S", field_name_str),
                ));
                trait_methods.push(quote! {
                    fn #write_fn(&mut self, val: u32) {
                        let cur = self.reg().#field_name.get();
                        self.reg().#field_name.set(cur | val);
                    }
                });
            } else {
                // RW / WO / mixed: mask and set
                let mask = compute_writable_mask(reg);
                if mask == 0xFFFFFFFF {
                    trait_methods.push(quote! {
                        fn #write_fn(&mut self, val: u32) {
                            self.reg().#field_name.set(val);
                        }
                    });
                } else {
                    let mask_lit = syn::LitInt::new(&format!("0x{:X}", mask), Span::call_site());
                    trait_methods.push(quote! {
                        fn #write_fn(&mut self, val: u32) {
                            self.reg().#field_name.set(val & #mask_lit);
                        }
                    });
                }
            }
        } // end scalar case
    } // end for reg

    let trait_def = quote! {
        pub trait #trait_name {
            fn reg(&self) -> &#regs_struct_name;

            #(#trait_methods)*

            fn poll(&mut self) {}
        }
    };

    // ── XxxDevice<T> struct + impls ─────────────────────────────────
    let mut read_arms = Vec::<TokenStream>::new();
    let mut write_arms = Vec::<TokenStream>::new();

    for item in &block.items {
        match item {
            BlockItem::Reg(reg) => {
                let offset_lit =
                    syn::LitInt::new(&format!("0x{:02X}", reg.offset), Span::call_site());
                let read_fn = format_ident!("read_{}", reg.name.to_lowercase());
                let write_fn = format_ident!("write_{}", reg.name.to_lowercase());

                if let Some(count) = reg.count {
                    let end_lit = syn::LitInt::new(
                        &format!("0x{:02X}", reg.offset + count * 4),
                        Span::call_site(),
                    );
                    read_arms.push(quote! { o @ #offset_lit..#end_lit if o % 4 == 0 => self.periph.#read_fn(((o - #offset_lit) / 4) as usize), });
                    write_arms.push(quote! { o @ #offset_lit..#end_lit if o % 4 == 0 => self.periph.#write_fn(((o - #offset_lit) / 4) as usize, val), });
                } else {
                    read_arms.push(quote! { #offset_lit => self.periph.#read_fn(), });
                    write_arms.push(quote! { #offset_lit => self.periph.#write_fn(val), });
                }
            }
            BlockItem::RegFile(rf) => {
                // Regfile arrays: word-level access via backing memory
                let start_lit =
                    syn::LitInt::new(&format!("0x{:02X}", rf.offset), Span::call_site());
                let end_lit = syn::LitInt::new(
                    &format!("0x{:02X}", rf.offset + rf.count * rf.stride),
                    Span::call_site(),
                );

                read_arms.push(quote! {
                    o @ #start_lit..#end_lit if o % 4 == 0 => {
                        let ptr = self.periph.reg() as *const #regs_struct_name as *const u8;
                        unsafe { core::ptr::read(ptr.add(o as usize) as *const u32) }
                    }
                });
                write_arms.push(quote! {
                    o @ #start_lit..#end_lit if o % 4 == 0 => {
                        let ptr = self.periph.reg() as *const #regs_struct_name as *mut u8;
                        unsafe { core::ptr::write(ptr.add(o as usize) as *mut u32, val) }
                    }
                });
            }
            BlockItem::Mem(m) => {
                // Memory regions: byte-level access via backing memory
                let start_lit = syn::LitInt::new(&format!("0x{:02X}", m.offset), Span::call_site());
                let end_lit = syn::LitInt::new(
                    &format!("0x{:02X}", m.offset + m.count * m.stride),
                    Span::call_site(),
                );

                read_arms.push(quote! {
                    o @ #start_lit..#end_lit if o % 4 == 0 => {
                        let ptr = self.periph.reg() as *const #regs_struct_name as *const u8;
                        unsafe { core::ptr::read(ptr.add(o as usize) as *const u32) }
                    }
                });
                write_arms.push(quote! {
                    o @ #start_lit..#end_lit if o % 4 == 0 => {
                        let ptr = self.periph.reg() as *const #regs_struct_name as *mut u8;
                        unsafe { core::ptr::write(ptr.add(o as usize) as *mut u32, val) }
                    }
                });
            }
        }
    }

    let device_def = quote! {
        pub struct #device_name<T: #trait_name> {
            pub periph: T,
            base: u32,
        }

        impl<T: #trait_name> #device_name<T> {
            pub fn new(base: u32, periph: T) -> Self {
                Self {
                    periph,
                    base,
                }
            }
        }

        #[allow(clippy::identity_op, clippy::single_match)]
        impl<T: #trait_name> BusDevice for #device_name<T> {
            fn base(&self) -> u32 {
                self.base
            }

            fn size(&self) -> u32 {
                #size_lit
            }

            fn read(&mut self, addr: u32) -> Result<u32, BusError> {
                Ok(match addr - self.base {
                    #(#read_arms)*
                    _ => 0,
                })
            }

            fn write(&mut self, addr: u32, val: u32) -> Result<(), BusError> {
                match addr - self.base {
                    #(#write_arms)*
                    _ => {}
                }
                Ok(())
            }

            fn poll(&mut self) {
                self.periph.poll();
            }

            fn backing_mem(&self) -> Option<*mut u8> {
                Some(self.periph.reg() as *const #regs_struct_name as *mut u8)
            }
        }
    };

    // Combine, fixup spacing, rustfmt
    let code = quote! {
        #imports_and_consts
        #trait_def
        #device_def
    };

    let mut formatted = crate::run_rustfmt(&crate::fixup_quote_spacing(&code.to_string()));

    // Add inline comments (quote can't generate comments)
    for (pattern, replacement) in &trait_comments {
        formatted = formatted.replace(pattern.as_str(), replacement.as_str());
    }

    format!("{}{}", header, formatted)
}

/// Compute writable bit mask from fields (only RW/WO/W1C/W1S fields contribute).
fn compute_writable_mask(reg: &Register) -> u32 {
    let mut mask = 0u32;
    for field in &reg.fields {
        if field.access != FieldAccess::RO {
            let field_mask = ((1u64 << field.width) - 1) as u32;
            mask |= field_mask << field.offset;
        }
    }
    mask
}

/// Compute the total size of a register block in bytes.
///
/// Returns the byte offset just past the last register (or last array element).
/// Rounds up to the next power of 2 for alignment.
fn compute_block_size(block: &RegisterBlock) -> u32 {
    let mut end = 0u32;
    for item in &block.items {
        end = end.max(item.end_offset());
    }
    end.max(0x10)
}

/// Generate peripheral code for all blocks in the schema.
///
/// Returns a list of `(filename_stem, code)` pairs.
pub fn generate(schema: &SocSchema, regs_crate: &str, bus_crate: &str) -> Vec<(String, String)> {
    let mut files: Vec<(String, String)> = schema
        .blocks
        .iter()
        .map(|b| (b.name.clone(), generate_block(b, regs_crate, bus_crate)))
        .collect();

    // Generate mod.rs
    let mod_items: Vec<TokenStream> = files
        .iter()
        .map(|(name, _)| {
            let ident = format_ident!("{}", name);
            quote! { pub mod #ident; }
        })
        .collect();
    let mod_code = quote! { #(#mod_items)* };
    let mod_str = format!(
        "{}\n{}",
        HEADER,
        crate::run_rustfmt(&crate::fixup_quote_spacing(&mod_code.to_string()))
    );
    files.push(("lib".to_string(), mod_str));

    files
}

fn to_pascal_case(s: &str) -> String {
    s.split('_')
        .map(|part| {
            let mut c = part.chars();
            match c.next() {
                None => String::new(),
                Some(first) => first.to_uppercase().collect::<String>() + c.as_str(),
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::schema::*;

    #[test]
    fn generate_peripheral_with_w1c() {
        let block = RegisterBlock {
            name: "my_timer".to_string(),
            base_addr: 0x4000_0000,
            items: vec![
                BlockItem::Reg(Register {
                    name: "CR".to_string(),
                    offset: 0x00,
                    fields: vec![
                        Field {
                            name: "EN".to_string(),
                            offset: 0,
                            width: 1,
                            access: FieldAccess::RW,
                            reset: 0,
                            desc: String::new(),
                        },
                        Field {
                            name: "IE".to_string(),
                            offset: 1,
                            width: 1,
                            access: FieldAccess::RW,
                            reset: 0,
                            desc: String::new(),
                        },
                    ],
                    desc: String::new(),
                    count: None,
                }),
                BlockItem::Reg(Register {
                    name: "SR".to_string(),
                    offset: 0x04,
                    fields: vec![Field {
                        name: "MATCH_FLAG".to_string(),
                        offset: 0,
                        width: 1,
                        access: FieldAccess::W1C,
                        reset: 0,
                        desc: String::new(),
                    }],
                    desc: String::new(),
                    count: None,
                }),
                BlockItem::Reg(Register {
                    name: "CNT".to_string(),
                    offset: 0x08,
                    fields: vec![Field {
                        name: "COUNT".to_string(),
                        offset: 0,
                        width: 32,
                        access: FieldAccess::RO,
                        reset: 0,
                        desc: String::new(),
                    }],
                    desc: String::new(),
                    count: None,
                }),
            ],
            desc: String::new(),
        };

        let code = generate_block(&block, "azihsm_test_soc_regs", "azihsm_test_bus");

        // Check imports — no more InMemoryRegister
        assert!(code.contains("use azihsm_test_soc_regs::my_timer::*;"));
        assert!(!code.contains("InMemoryRegister"));

        // Check re-export of MMIO struct
        assert!(code.contains("pub use azihsm_test_soc_regs::my_timer::regs::MyTimerRegs;"));

        // Check trait uses &self (not &mut self) and references MyTimerRegs
        assert!(code.contains("pub trait MyTimer {"));
        assert!(code.contains("fn reg(&self) -> &MyTimerRegs;"));
        assert!(code.contains("self.reg().cr.get()"));
        assert!(code.contains("fn write_cr(&mut self, val: u32)"));
        assert!(code.contains(".set(val & 0x3)")); // RW with 2-bit mask

        // Check W1C uses get/set pattern
        assert!(code.contains("self.reg().sr.get()"));
        assert!(code.contains("self.reg().sr.set(cur & !val); // W1C"));

        // Check RO
        assert!(code.contains("fn write_cnt(&mut self, _val: u32) {} // RO"));

        // Check device struct
        assert!(code.contains("pub struct MyTimerDevice<T: MyTimer>"));

        // Check BusDevice dispatch
        assert!(code.contains("self.periph.read_cr()"));
        assert!(code.contains("self.periph.write_sr(val)"));
        assert!(code.contains("self.periph.poll()"));

        // Check backing_mem uses trait reg()
        assert!(code.contains("self.periph.reg()"));
    }
}
