// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! Generate tock-style register definitions from a [`SocSchema`](crate::schema::SocSchema).
//!
//! Output format uses `tock_registers::register_bitfields!` macros.

use proc_macro2::Literal;
use proc_macro2::Span;
use proc_macro2::TokenStream;
use quote::format_ident;
use quote::quote;

use crate::schema::BlockItem;
use crate::schema::Field;
use crate::schema::FieldAccess;
use crate::schema::RegisterBlock;
use crate::schema::SocSchema;

const HEADER: &str = "\
    // Copyright (c) Microsoft Corporation.\n\
    // Licensed under the MIT License.\n\
    // AUTO-GENERATED by azihsm_reggen — do not edit.\n";

/// Generate firmware register code for a single peripheral.
pub fn generate_block(block: &RegisterBlock) -> String {
    let upper_name = block.name.to_uppercase();

    // Header (raw string — quote can't generate comments)
    let mut header = format!("{}\n//! Register definitions for {}.\n", HEADER, block.name);
    if !crate::sanitize_desc(&block.desc).is_empty() {
        header.push_str(&format!("//!\n//! {}\n", crate::sanitize_desc(&block.desc)));
    }
    header.push('\n');

    // Constants via quote
    let base_ident = format_ident!("{}_BASE", upper_name);
    let base_lit = syn::LitInt::new(&format!("0x{:08X}", block.base_addr), Span::call_site());

    let offset_consts: Vec<TokenStream> = block
        .registers()
        .map(|reg| {
            let name = format_ident!("{}_OFFSET", reg.name);
            let lit = syn::LitInt::new(&format!("0x{:02X}", reg.offset), Span::call_site());
            quote! { pub const #name: u32 = #lit; }
        })
        .collect();

    let regfile_consts: Vec<TokenStream> = block
        .regfiles()
        .map(|rf| {
            let name = format_ident!("{}_OFFSET", rf.name);
            let lit = syn::LitInt::new(&format!("0x{:02X}", rf.offset), Span::call_site());
            let count_name = format_ident!("{}_COUNT", rf.name);
            let count_lit = syn::LitInt::new(&format!("{}", rf.count), Span::call_site());
            let stride_name = format_ident!("{}_STRIDE", rf.name);
            let stride_lit = syn::LitInt::new(&format!("0x{:02X}", rf.stride), Span::call_site());
            quote! {
                pub const #name: u32 = #lit;
                pub const #count_name: u32 = #count_lit;
                pub const #stride_name: u32 = #stride_lit;
            }
        })
        .collect();

    let mem_consts: Vec<TokenStream> = block
        .mem_regions()
        .map(|m| {
            let name = format_ident!("{}_OFFSET", m.name);
            let lit = syn::LitInt::new(&format!("0x{:02X}", m.offset), Span::call_site());
            let count_name = format_ident!("{}_COUNT", m.name);
            let count_lit = syn::LitInt::new(&format!("{}", m.count), Span::call_site());
            let stride_name = format_ident!("{}_STRIDE", m.name);
            let stride_lit = syn::LitInt::new(&format!("0x{:02X}", m.stride), Span::call_site());
            let size_name = format_ident!("{}_SIZE", m.name);
            let size_lit = syn::LitInt::new(&format!("0x{:02X}", m.entry_size), Span::call_site());
            quote! {
                pub const #name: u32 = #lit;
                pub const #count_name: u32 = #count_lit;
                pub const #stride_name: u32 = #stride_lit;
                pub const #size_name: u32 = #size_lit;
            }
        })
        .collect();

    let consts = quote! {
        pub const #base_ident: u32 = #base_lit;
        #(#offset_consts)*
        #(#regfile_consts)*
        #(#mem_consts)*
    };
    let consts_str = crate::run_rustfmt(&crate::fixup_quote_spacing(&consts.to_string()));

    // register_bitfields! macro (quote for tokens, manual formatting for DSL layout)
    let bitfields_str = build_bitfields(block);

    // regfile entry structs
    let regfile_structs_str = build_regfile_structs(block);

    // register_structs! macro for MMIO struct layout
    let structs_str = build_register_structs(block);

    // Combine sections, trimming trailing whitespace from each to avoid
    // double-blank-lines that would fail rustfmt.
    let mut parts: Vec<&str> = vec![&header, &consts_str, &bitfields_str];
    if !regfile_structs_str.is_empty() {
        parts.push(&regfile_structs_str);
    }
    parts.push(&structs_str);

    let trimmed: Vec<&str> = parts
        .iter()
        .map(|s| s.trim())
        .filter(|s| !s.is_empty())
        .collect();
    format!("{}\n", trimmed.join("\n\n"))
}

/// Build the `tock_registers::register_structs!` invocation inside a `regs` submodule.
///
/// Generates a MMIO-compatible struct using tock `ReadWrite`, `ReadOnly`, or
/// `WriteOnly` register types, with `_reserved` padding for gaps between
/// registers and an `@END` marker.
///
/// Caliptra pattern:
/// ```ignore
/// pub mod regs {
///     tock_registers::register_structs! {
///         pub MatchTimer {
///             (0x0 => pub timer_cr: ReadWrite<u32, super::TIMER_CR::Register>),
///             (0x10 => @END),
///         }
///     }
/// }
/// ```
/// Check if a register child has meaningful bitfields (more than one field,
/// or a single field that doesn't span all 32 bits).
fn child_has_bitfields(reg: &crate::schema::Register) -> bool {
    if reg.fields.len() > 1 {
        return true;
    }
    if let Some(f) = reg.fields.first() {
        // Single field not spanning all 32 bits
        return f.width < 32;
    }
    false
}

/// Generate the bitfield name for a regfile child register.
/// Uses REGFILE_CHILD format to avoid collisions (e.g., ICQ_ENTRY_INFO).
fn regfile_child_bitfield_name(rf_type: &str, child_name: &str) -> String {
    format!(
        "{}_{}",
        rf_type.to_uppercase().replace("_ENTRY", ""),
        child_name
    )
}

/// Build `#[repr(C)]` structs for each unique regfile type.
///
/// Each regfile produces a struct with child registers as typed fields.
/// Children with bitfields use `crate::RW<u32, super::BITFIELD::Register>`,
/// others use plain `u32`. Padding is inserted for gaps.
fn build_regfile_structs(block: &RegisterBlock) -> String {
    let mut out = String::new();
    let mut seen_types = std::collections::HashSet::new();

    for rf in block.regfiles() {
        if !seen_types.insert(rf.type_name.clone()) {
            continue;
        }

        let struct_name = to_pascal_case(&rf.type_name);

        out.push_str(&format!(
            "/// Regfile entry struct for `{}`.\n",
            rf.type_name
        ));
        out.push_str("#[repr(C)]\n");
        out.push_str(&format!("pub struct {} {{\n", struct_name));

        let mut next_offset: u32 = 0;
        let mut pad_idx: u32 = 0;

        for child in &rf.children {
            // Insert padding if there's a gap
            if child.offset > next_offset {
                let gap = child.offset - next_offset;
                let gap_words = gap / 4;
                if gap_words == 1 {
                    out.push_str(&format!("    _pad{}: u32,\n", pad_idx));
                } else {
                    out.push_str(&format!("    _pad{}: [u32; {}],\n", pad_idx, gap_words));
                }
                pad_idx += 1;
            }

            let field_name = escape_keyword(&child.name.to_lowercase());
            let reg_type = match child.combined_access() {
                FieldAccess::RO => "crate::RO",
                FieldAccess::WO => "crate::WO",
                _ => "crate::RW",
            };
            if child_has_bitfields(child) {
                let bitfield_name = regfile_child_bitfield_name(&rf.type_name, &child.name);
                out.push_str(&format!(
                    "    pub {}: {}<u32, {}::Register>,\n",
                    field_name, reg_type, bitfield_name
                ));
            } else {
                out.push_str(&format!("    pub {}: {}<u32>,\n", field_name, reg_type));
            }
            next_offset = child.offset + 4;
        }

        // Trailing padding to fill stride
        if rf.stride > next_offset {
            let gap = rf.stride - next_offset;
            let gap_words = gap / 4;
            if gap_words == 1 {
                out.push_str(&format!("    _pad{}: u32,\n", pad_idx));
            } else if gap_words > 1 {
                out.push_str(&format!("    _pad{}: [u32; {}],\n", pad_idx, gap_words));
            }
        }

        out.push_str("}\n\n");
    }

    out
}

fn build_register_structs(block: &RegisterBlock) -> String {
    let struct_name = format!("{}Regs", to_pascal_case(&block.name));

    let mut out = String::new();
    out.push_str("pub mod regs {\n");
    out.push_str("    //! MMIO register struct for firmware use.\n");
    out.push_str("    tock_registers::register_structs! {\n");
    out.push_str(&format!("        pub {} {{\n", struct_name));

    let mut next_offset: u32 = 0;
    let mut reserved_idx: u32 = 0;

    for item in &block.items {
        let item_offset = item.offset();

        // Insert reserved padding if there's a gap
        if item_offset > next_offset {
            out.push_str(&format!(
                "            (0x{:x} => _reserved{}),\n",
                next_offset, reserved_idx
            ));
            reserved_idx += 1;
        }

        match item {
            BlockItem::Reg(reg) => {
                let field_name = escape_keyword(&reg.name.to_lowercase());
                let reg_type = match reg.combined_access() {
                    FieldAccess::RO => "crate::RO",
                    FieldAccess::WO => "crate::WO",
                    _ => "crate::RW",
                };
                let bitfield_name = &reg.name;

                if let Some(count) = reg.count {
                    out.push_str(&format!(
                        "            (0x{:x} => pub {}: [{}<u32, super::{}::Register>; {}]),\n",
                        reg.offset, field_name, reg_type, bitfield_name, count
                    ));
                    next_offset = reg.offset + 4 * count;
                } else {
                    out.push_str(&format!(
                        "            (0x{:x} => pub {}: {}<u32, super::{}::Register>),\n",
                        reg.offset, field_name, reg_type, bitfield_name
                    ));
                    next_offset = reg.offset + 4;
                }
            }
            BlockItem::RegFile(rf) => {
                let field_name = escape_keyword(&rf.name.to_lowercase());
                let struct_type = to_pascal_case(&rf.type_name);

                out.push_str(&format!(
                    "            (0x{:x} => pub {}: [super::{}; {}]),\n",
                    rf.offset, field_name, struct_type, rf.count
                ));
                next_offset = rf.offset + rf.count * rf.stride;
            }
            BlockItem::Mem(m) => {
                // Mem regions are emitted as pub byte arrays
                let field_name = escape_keyword(&m.name.to_lowercase());
                let total_bytes = m.count * m.stride;

                out.push_str(&format!(
                    "            (0x{:x} => pub {}: [u8; {}]),\n",
                    m.offset, field_name, total_bytes
                ));
                next_offset = m.offset + total_bytes;
            }
        }
    }

    // @END at next_offset (right after the last item)
    out.push_str(&format!("            (0x{:x} => @END),\n", next_offset));
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n");
    out
}

/// Convert snake_case to PascalCase.
fn to_pascal_case(s: &str) -> String {
    s.split('_')
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                None => String::new(),
                Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect()
}

/// Escape Rust keywords by prefixing with `r#`.
fn escape_keyword(name: &str) -> String {
    const KEYWORDS: &[&str] = &[
        "as", "break", "const", "continue", "crate", "else", "enum", "extern", "false", "fn",
        "for", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub", "ref",
        "return", "self", "static", "struct", "super", "trait", "true", "type", "unsafe", "use",
        "where", "while", "async", "await", "dyn", "abstract", "become", "box", "do", "final",
        "macro", "override", "priv", "typeof", "unsized", "virtual", "yield", "try",
    ];
    if KEYWORDS.contains(&name) {
        format!("r#{}", name)
    } else {
        name.to_string()
    }
}

/// Build the `tock_registers::register_bitfields!` invocation.
///
/// Uses `quote!` to produce the individual field identifiers and literals,
/// then assembles the DSL layout manually (since `TokenStream::to_string()`
/// does not preserve indentation).
fn build_bitfields(block: &RegisterBlock) -> String {
    let regs: Vec<&crate::schema::Register> = block.registers().collect();

    // Also collect regfile child registers that have meaningful bitfields
    let mut regfile_children: Vec<(&str, &crate::schema::Register)> = Vec::new();
    let mut seen_rf_types = std::collections::HashSet::new();
    for rf in block.regfiles() {
        if !seen_rf_types.insert(rf.type_name.clone()) {
            continue;
        }
        for child in &rf.children {
            if child_has_bitfields(child) {
                regfile_children.push((&rf.type_name, child));
            }
        }
    }

    let total = regs.len() + regfile_children.len();
    if total == 0 {
        return String::new();
    }

    let mut out = String::from("tock_registers::register_bitfields! [u32,\n");
    let mut idx = 0;

    for reg in &regs {
        if !crate::sanitize_desc(&reg.desc).is_empty() {
            out.push_str(&format!("    /// {}\n", crate::sanitize_desc(&reg.desc)));
        }
        let reg_name = format_ident!("{}", reg.name);
        out.push_str(&format!("    pub {} [\n", reg_name));

        for field in &reg.fields {
            let field_str = emit_field_tokens(field);
            if !crate::sanitize_desc(&field.desc).is_empty() {
                out.push_str(&format!(
                    "        /// {}\n",
                    crate::sanitize_desc(&field.desc)
                ));
            }
            out.push_str(&format!("        {},\n", field_str));
        }

        out.push_str("    ]");
        idx += 1;
        if idx < total {
            out.push(',');
        }
        out.push('\n');
    }

    // Emit bitfields for regfile child registers
    for (rf_type, child) in &regfile_children {
        let bitfield_name = regfile_child_bitfield_name(rf_type, &child.name);
        if !crate::sanitize_desc(&child.desc).is_empty() {
            out.push_str(&format!("    /// {}\n", crate::sanitize_desc(&child.desc)));
        }
        out.push_str(&format!("    pub {} [\n", bitfield_name));

        for field in &child.fields {
            let field_str = emit_field_tokens(field);
            if !crate::sanitize_desc(&field.desc).is_empty() {
                out.push_str(&format!(
                    "        /// {}\n",
                    crate::sanitize_desc(&field.desc)
                ));
            }
            out.push_str(&format!("        {},\n", field_str));
        }

        out.push_str("    ]");
        idx += 1;
        if idx < total {
            out.push(',');
        }
        out.push('\n');
    }

    out.push_str("];\n");
    out
}

/// Emit a single field definition as a string using `quote!` identifiers and
/// literals, then fix up the spacing that `TokenStream::to_string()` introduces
/// around parenthesised groups.
fn emit_field_tokens(field: &Field) -> String {
    let fname = format_ident!("{}", field.name);
    let offset_kw = format_ident!("OFFSET");
    let numbits_kw = format_ident!("NUMBITS");
    let off = Literal::u32_unsuffixed(field.offset);
    let width = Literal::u32_unsuffixed(field.width);

    let ts = quote! { #fname #offset_kw(#off) #numbits_kw(#width) [] };
    crate::fixup_quote_spacing(&ts.to_string())
}

/// Generate firmware register code for all peripherals in the schema.
///
/// Returns a list of `(filename_stem, code)` pairs.
pub fn generate(schema: &SocSchema) -> Vec<(String, String)> {
    let mut files: Vec<(String, String)> = schema
        .blocks
        .iter()
        .map(|b| (b.name.clone(), generate_block(b)))
        .collect();

    // Generate mod.rs
    let mod_items: Vec<TokenStream> = files
        .iter()
        .map(|(name, _)| {
            let ident = format_ident!("{}", name);
            quote! { pub mod #ident; }
        })
        .collect();
    let mod_code = quote! { #(#mod_items)* };
    let access_aliases = [
        "/// Register access type aliases.",
        "///",
        "/// With the `emu` feature enabled (used by the emulator's device crate),",
        "/// all register types become `ReadWrite` so the emulator can read and",
        "/// write all registers through the backing store. Without the feature,",
        "/// registers use their correct access types (`ReadOnly`, `WriteOnly`).",
        "#[cfg(feature = \"emu\")]",
        "mod access {",
        "    pub type RW<T, R = ()> = tock_registers::registers::ReadWrite<T, R>;",
        "    pub type RO<T, R = ()> = tock_registers::registers::ReadWrite<T, R>;",
        "    pub type WO<T, R = ()> = tock_registers::registers::ReadWrite<T, R>;",
        "}",
        "",
        "#[cfg(not(feature = \"emu\"))]",
        "mod access {",
        "    pub type RW<T, R = ()> = tock_registers::registers::ReadWrite<T, R>;",
        "    pub type RO<T, R = ()> = tock_registers::registers::ReadOnly<T, R>;",
        "    pub type WO<T, R = ()> = tock_registers::registers::WriteOnly<T, R>;",
        "}",
        "",
        "pub use access::*;",
    ]
    .join("\n");
    let formatted_mods = crate::run_rustfmt(&crate::fixup_quote_spacing(&mod_code.to_string()));
    let mod_str = format!(
        "{}\n#![no_std]\n#![allow(clippy::modulo_one)]\n\n{}\n{}",
        HEADER, access_aliases, formatted_mods,
    );
    files.push(("lib".to_string(), mod_str));

    files
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::schema::*;

    #[test]
    fn generate_simple_block() {
        let block = RegisterBlock {
            name: "my_timer".to_string(),
            base_addr: 0x4000_0000,
            items: vec![
                BlockItem::Reg(Register {
                    name: "CR".to_string(),
                    offset: 0x00,
                    fields: vec![
                        Field {
                            name: "EN".to_string(),
                            offset: 0,
                            width: 1,
                            access: FieldAccess::RW,
                            reset: 0,
                            desc: "Enable".to_string(),
                        },
                        Field {
                            name: "IE".to_string(),
                            offset: 1,
                            width: 1,
                            access: FieldAccess::RW,
                            reset: 0,
                            desc: "Interrupt enable".to_string(),
                        },
                    ],
                    desc: "Control register".to_string(),
                    count: None,
                }),
                BlockItem::Reg(Register {
                    name: "SR".to_string(),
                    offset: 0x04,
                    fields: vec![Field {
                        name: "MATCH_FLAG".to_string(),
                        offset: 0,
                        width: 1,
                        access: FieldAccess::W1C,
                        reset: 0,
                        desc: "Match flag".to_string(),
                    }],
                    desc: "Status register".to_string(),
                    count: None,
                }),
            ],
            desc: "Simple timer".to_string(),
        };

        let code = generate_block(&block);

        assert!(code.contains("pub const MY_TIMER_BASE: u32 = 0x40000000;"));
        assert!(code.contains("pub const CR_OFFSET: u32 = 0x00;"));
        assert!(code.contains("pub const SR_OFFSET: u32 = 0x04;"));
        assert!(code.contains("register_bitfields! [u32,"));
        assert!(code.contains("EN OFFSET(0) NUMBITS(1)"));
        assert!(code.contains("IE OFFSET(1) NUMBITS(1)"));
        assert!(code.contains("MATCH_FLAG OFFSET(0) NUMBITS(1)"));

        // register_structs! output
        assert!(code.contains("pub mod regs {"));
        assert!(code.contains("register_structs!"));
        assert!(code.contains("pub MyTimerRegs {"));
        assert!(code.contains("pub cr: crate::RW<u32, super::CR::Register>"));
        assert!(code.contains("pub sr: crate::RW<u32, super::SR::Register>"));
        assert!(code.contains("@END"));
    }

    #[test]
    fn register_structs_read_only_field() {
        let block = RegisterBlock {
            name: "sensor".to_string(),
            base_addr: 0x5000_0000,
            items: vec![BlockItem::Reg(Register {
                name: "DATA".to_string(),
                offset: 0x00,
                fields: vec![Field {
                    name: "VALUE".to_string(),
                    offset: 0,
                    width: 16,
                    access: FieldAccess::RO,
                    reset: 0,
                    desc: "Sensor data".to_string(),
                }],
                desc: "Data register".to_string(),
                count: None,
            })],
            desc: "Sensor".to_string(),
        };

        let code = generate_block(&block);
        assert!(code.contains("pub data: crate::RO<u32"));
    }

    #[test]
    fn register_structs_reserved_gap() {
        let block = RegisterBlock {
            name: "gapped".to_string(),
            base_addr: 0x6000_0000,
            items: vec![
                BlockItem::Reg(Register {
                    name: "A".to_string(),
                    offset: 0x00,
                    fields: vec![Field {
                        name: "VAL".to_string(),
                        offset: 0,
                        width: 32,
                        access: FieldAccess::RW,
                        reset: 0,
                        desc: String::new(),
                    }],
                    desc: String::new(),
                    count: None,
                }),
                BlockItem::Reg(Register {
                    name: "B".to_string(),
                    offset: 0x10,
                    fields: vec![Field {
                        name: "VAL".to_string(),
                        offset: 0,
                        width: 32,
                        access: FieldAccess::RW,
                        reset: 0,
                        desc: String::new(),
                    }],
                    desc: String::new(),
                    count: None,
                }),
            ],
            desc: String::new(),
        };

        let code = generate_block(&block);
        assert!(code.contains("_reserved0"));
        assert!(code.contains("(0x4 => _reserved0)"));
        assert!(code.contains("(0x10 => pub b:"));
    }
}
