// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! Cryptographically secure random number generation.
//!
//! This module provides platform-specific implementations of cryptographically
//! secure random number generators (CSPRNGs). The implementation automatically
//! selects the appropriate backend based on the target operating system:
//!
//! - **Linux**: Uses OpenSSL's `RAND_bytes` function via the `rand_ossl` module
//! - **Windows**: Uses Windows Cryptography API: Next Generation (CNG) via the `rand_cng` module
//!
//! All implementations provide the same interface through the [`RngOp`] trait,
//! ensuring consistent behavior across platforms while leveraging platform-specific
//! optimizations and security features.
//!
//! # Security
//!
//! All random number generators provided by this module are cryptographically
//! secure and suitable for:
//! - Generating cryptographic keys
//! - Creating initialization vectors (IVs)
//! - Producing nonces and salts
//! - Any other security-critical random values
//!
//! The implementations automatically handle proper seeding from system entropy
//! sources and provide forward secrecy guarantees.
//!
//! # Architecture
//!
//! The module uses conditional compilation to select the appropriate implementation:
//! - Platform detection is handled at compile time
//! - Each platform gets its optimized implementation
//! - Unsupported platforms result in compilation errors
//!
//! # Thread Safety
//!
//! All implementations are thread-safe and can be used concurrently from
//! multiple threads without additional synchronization.
// Platform-specific RNG implementations
// Each platform uses its native cryptographic API for optimal performance and security

#[cfg(target_os = "linux")]
mod rand_ossl;

#[cfg(target_os = "windows")]
mod rand_cng;

// Re-export CryptoError for use in RNG implementations
pub(crate) use crate::CryptoError;

/// Trait defining the interface for random number generation operations.
///
/// This trait provides a uniform interface for cryptographically secure random
/// number generation across different platforms and implementations. All
/// implementations must provide cryptographically secure random bytes suitable
/// for any cryptographic purpose.
///
/// # Implementation Requirements
///
/// Implementors must ensure that:
/// - Generated bytes are cryptographically secure
/// - The implementation is properly seeded from system entropy
/// - The generator provides forward secrecy
/// - The implementation is thread-safe
/// - Performance is suitable for cryptographic applications
///
/// # Design Rationale
///
/// The trait uses static methods rather than instance methods to:
/// - Avoid the need to manage RNG state
/// - Simplify the API for common use cases
/// - Allow implementations to use system-global RNG instances
/// - Reduce memory overhead for stateless implementations
pub trait RngOp {
    /// Fills a buffer with cryptographically secure random bytes.
    ///
    /// This method generates cryptographically strong random bytes and fills
    /// the provided buffer. The generated bytes are suitable for any
    /// cryptographic purpose including key generation, IV creation, and
    /// nonce generation.
    ///
    /// # Arguments
    ///
    /// * `buf` - A mutable byte slice to be filled with random data.
    ///
    /// # Returns
    ///
    /// * `Ok(())` - Random byte generation was successful
    /// * `Err(CryptoError::RngError)` - Random number generation failed
    ///
    /// # Errors
    ///
    /// This method returns `CryptoError::RngError` when:
    /// - The underlying RNG is not properly seeded
    /// - System entropy sources are unavailable
    /// - Platform-specific RNG failures occur
    /// - Memory allocation failures (platform-dependent)
    ///
    /// # Security Guarantees
    ///
    /// - Generated bytes are cryptographically secure
    /// - No timing information leakage
    /// - Forward secrecy is maintained
    /// - Proper entropy mixing and periodic reseeding
    ///
    /// # Performance
    ///
    /// The performance characteristics depend on the platform implementation:
    /// - Linux: Performance depends on OpenSSL and system entropy
    /// - Windows: Performance depends on CNG and system entropy
    /// - Generally suitable for most cryptographic applications
    fn rand_bytes(buf: &mut [u8]) -> Result<(), CryptoError>;
}

/// Default platform RNG type alias
#[cfg(target_os = "linux")]
pub type PlatformRng = rand_ossl::OsslRng;

/// Default platform RNG type alias
#[cfg(target_os = "windows")]
pub type PlatformRng = rand_cng::CngRng;

/// Cryptographically secure random number generator.
pub struct Rng;

impl Rng {
    /// Generates cryptographically secure random bytes using the platform-specific RNG.
    ///
    /// This method fills the provided buffer with cryptographically strong
    /// random bytes using the appropriate platform-specific implementation.
    ///
    /// # Arguments
    ///
    /// * `buf` - A mutable byte slice that will be filled with random data.
    ///
    /// # Returns
    ///
    /// * `Ok(())` - If random byte generation was successful
    /// * `Err(CryptoError::RngError)` - If random number generation fails
    pub fn rand_bytes(buf: &mut [u8]) -> Result<(), CryptoError> {
        PlatformRng::rand_bytes(buf)
    }

    /// Generates a vector of cryptographically secure random bytes.
    ///
    /// This method creates a new vector of the specified length and fills it
    /// with cryptographically strong random bytes using the platform-specific
    /// implementation.
    ///
    /// # Arguments
    ///
    /// * `len` - The desired length of the random byte vector.
    ///
    /// # Returns
    ///
    /// * `Ok(Vec<u8>)` - A vector filled with random bytes
    /// * `Err(CryptoError::RngError)` - If random number generation fails
    pub fn rand_vec(len: usize) -> Result<Vec<u8>, CryptoError> {
        let mut buf = vec![u8::default(); len];
        Self::rand_bytes(&mut buf)?;
        Ok(buf)
    }
}

/// Integration tests for random number generation functionality.
///
/// These tests verify that the platform-specific RNG implementations
/// work correctly and produce non-deterministic output.
#[cfg(test)]
mod tests;
